// Generated automatically by gen_mod_openbsm.c: do not touch!
// Copyright, license: see file gen_mod_openbsm.c.
#define OPENBSM_MAX_ARGS 128
#define OPENBSM_MAX_ENV 128
#define OPENBSM_MAX_GROUPS 16
#define F_OPENBSM_ARG_START F_OPENBSM_REGULAR_END
  { "openbsm.arg1", T_UINT, "openbsm argument 1" },
  { "openbsm.argname1", T_STR, "openbsm argument name 1" },
  { "openbsm.arg2", T_UINT, "openbsm argument 2" },
  { "openbsm.argname2", T_STR, "openbsm argument name 2" },
  { "openbsm.arg3", T_UINT, "openbsm argument 3" },
  { "openbsm.argname3", T_STR, "openbsm argument name 3" },
  { "openbsm.arg4", T_UINT, "openbsm argument 4" },
  { "openbsm.argname4", T_STR, "openbsm argument name 4" },
  { "openbsm.arg5", T_UINT, "openbsm argument 5" },
  { "openbsm.argname5", T_STR, "openbsm argument name 5" },
  { "openbsm.arg6", T_UINT, "openbsm argument 6" },
  { "openbsm.argname6", T_STR, "openbsm argument name 6" },
  { "openbsm.arg7", T_UINT, "openbsm argument 7" },
  { "openbsm.argname7", T_STR, "openbsm argument name 7" },
  { "openbsm.arg8", T_UINT, "openbsm argument 8" },
  { "openbsm.argname8", T_STR, "openbsm argument name 8" },
  { "openbsm.arg9", T_UINT, "openbsm argument 9" },
  { "openbsm.argname9", T_STR, "openbsm argument name 9" },
  { "openbsm.arg10", T_UINT, "openbsm argument 10" },
  { "openbsm.argname10", T_STR, "openbsm argument name 10" },
  { "openbsm.arg11", T_UINT, "openbsm argument 11" },
  { "openbsm.argname11", T_STR, "openbsm argument name 11" },
  { "openbsm.arg12", T_UINT, "openbsm argument 12" },
  { "openbsm.argname12", T_STR, "openbsm argument name 12" },
  { "openbsm.arg13", T_UINT, "openbsm argument 13" },
  { "openbsm.argname13", T_STR, "openbsm argument name 13" },
  { "openbsm.arg14", T_UINT, "openbsm argument 14" },
  { "openbsm.argname14", T_STR, "openbsm argument name 14" },
  { "openbsm.arg15", T_UINT, "openbsm argument 15" },
  { "openbsm.argname15", T_STR, "openbsm argument name 15" },
  { "openbsm.arg16", T_UINT, "openbsm argument 16" },
  { "openbsm.argname16", T_STR, "openbsm argument name 16" },
  { "openbsm.arg17", T_UINT, "openbsm argument 17" },
  { "openbsm.argname17", T_STR, "openbsm argument name 17" },
  { "openbsm.arg18", T_UINT, "openbsm argument 18" },
  { "openbsm.argname18", T_STR, "openbsm argument name 18" },
  { "openbsm.arg19", T_UINT, "openbsm argument 19" },
  { "openbsm.argname19", T_STR, "openbsm argument name 19" },
  { "openbsm.arg20", T_UINT, "openbsm argument 20" },
  { "openbsm.argname20", T_STR, "openbsm argument name 20" },
  { "openbsm.arg21", T_UINT, "openbsm argument 21" },
  { "openbsm.argname21", T_STR, "openbsm argument name 21" },
  { "openbsm.arg22", T_UINT, "openbsm argument 22" },
  { "openbsm.argname22", T_STR, "openbsm argument name 22" },
  { "openbsm.arg23", T_UINT, "openbsm argument 23" },
  { "openbsm.argname23", T_STR, "openbsm argument name 23" },
  { "openbsm.arg24", T_UINT, "openbsm argument 24" },
  { "openbsm.argname24", T_STR, "openbsm argument name 24" },
  { "openbsm.arg25", T_UINT, "openbsm argument 25" },
  { "openbsm.argname25", T_STR, "openbsm argument name 25" },
  { "openbsm.arg26", T_UINT, "openbsm argument 26" },
  { "openbsm.argname26", T_STR, "openbsm argument name 26" },
  { "openbsm.arg27", T_UINT, "openbsm argument 27" },
  { "openbsm.argname27", T_STR, "openbsm argument name 27" },
  { "openbsm.arg28", T_UINT, "openbsm argument 28" },
  { "openbsm.argname28", T_STR, "openbsm argument name 28" },
  { "openbsm.arg29", T_UINT, "openbsm argument 29" },
  { "openbsm.argname29", T_STR, "openbsm argument name 29" },
  { "openbsm.arg30", T_UINT, "openbsm argument 30" },
  { "openbsm.argname30", T_STR, "openbsm argument name 30" },
  { "openbsm.arg31", T_UINT, "openbsm argument 31" },
  { "openbsm.argname31", T_STR, "openbsm argument name 31" },
  { "openbsm.arg32", T_UINT, "openbsm argument 32" },
  { "openbsm.argname32", T_STR, "openbsm argument name 32" },
  { "openbsm.arg33", T_UINT, "openbsm argument 33" },
  { "openbsm.argname33", T_STR, "openbsm argument name 33" },
  { "openbsm.arg34", T_UINT, "openbsm argument 34" },
  { "openbsm.argname34", T_STR, "openbsm argument name 34" },
  { "openbsm.arg35", T_UINT, "openbsm argument 35" },
  { "openbsm.argname35", T_STR, "openbsm argument name 35" },
  { "openbsm.arg36", T_UINT, "openbsm argument 36" },
  { "openbsm.argname36", T_STR, "openbsm argument name 36" },
  { "openbsm.arg37", T_UINT, "openbsm argument 37" },
  { "openbsm.argname37", T_STR, "openbsm argument name 37" },
  { "openbsm.arg38", T_UINT, "openbsm argument 38" },
  { "openbsm.argname38", T_STR, "openbsm argument name 38" },
  { "openbsm.arg39", T_UINT, "openbsm argument 39" },
  { "openbsm.argname39", T_STR, "openbsm argument name 39" },
  { "openbsm.arg40", T_UINT, "openbsm argument 40" },
  { "openbsm.argname40", T_STR, "openbsm argument name 40" },
  { "openbsm.arg41", T_UINT, "openbsm argument 41" },
  { "openbsm.argname41", T_STR, "openbsm argument name 41" },
  { "openbsm.arg42", T_UINT, "openbsm argument 42" },
  { "openbsm.argname42", T_STR, "openbsm argument name 42" },
  { "openbsm.arg43", T_UINT, "openbsm argument 43" },
  { "openbsm.argname43", T_STR, "openbsm argument name 43" },
  { "openbsm.arg44", T_UINT, "openbsm argument 44" },
  { "openbsm.argname44", T_STR, "openbsm argument name 44" },
  { "openbsm.arg45", T_UINT, "openbsm argument 45" },
  { "openbsm.argname45", T_STR, "openbsm argument name 45" },
  { "openbsm.arg46", T_UINT, "openbsm argument 46" },
  { "openbsm.argname46", T_STR, "openbsm argument name 46" },
  { "openbsm.arg47", T_UINT, "openbsm argument 47" },
  { "openbsm.argname47", T_STR, "openbsm argument name 47" },
  { "openbsm.arg48", T_UINT, "openbsm argument 48" },
  { "openbsm.argname48", T_STR, "openbsm argument name 48" },
  { "openbsm.arg49", T_UINT, "openbsm argument 49" },
  { "openbsm.argname49", T_STR, "openbsm argument name 49" },
  { "openbsm.arg50", T_UINT, "openbsm argument 50" },
  { "openbsm.argname50", T_STR, "openbsm argument name 50" },
  { "openbsm.arg51", T_UINT, "openbsm argument 51" },
  { "openbsm.argname51", T_STR, "openbsm argument name 51" },
  { "openbsm.arg52", T_UINT, "openbsm argument 52" },
  { "openbsm.argname52", T_STR, "openbsm argument name 52" },
  { "openbsm.arg53", T_UINT, "openbsm argument 53" },
  { "openbsm.argname53", T_STR, "openbsm argument name 53" },
  { "openbsm.arg54", T_UINT, "openbsm argument 54" },
  { "openbsm.argname54", T_STR, "openbsm argument name 54" },
  { "openbsm.arg55", T_UINT, "openbsm argument 55" },
  { "openbsm.argname55", T_STR, "openbsm argument name 55" },
  { "openbsm.arg56", T_UINT, "openbsm argument 56" },
  { "openbsm.argname56", T_STR, "openbsm argument name 56" },
  { "openbsm.arg57", T_UINT, "openbsm argument 57" },
  { "openbsm.argname57", T_STR, "openbsm argument name 57" },
  { "openbsm.arg58", T_UINT, "openbsm argument 58" },
  { "openbsm.argname58", T_STR, "openbsm argument name 58" },
  { "openbsm.arg59", T_UINT, "openbsm argument 59" },
  { "openbsm.argname59", T_STR, "openbsm argument name 59" },
  { "openbsm.arg60", T_UINT, "openbsm argument 60" },
  { "openbsm.argname60", T_STR, "openbsm argument name 60" },
  { "openbsm.arg61", T_UINT, "openbsm argument 61" },
  { "openbsm.argname61", T_STR, "openbsm argument name 61" },
  { "openbsm.arg62", T_UINT, "openbsm argument 62" },
  { "openbsm.argname62", T_STR, "openbsm argument name 62" },
  { "openbsm.arg63", T_UINT, "openbsm argument 63" },
  { "openbsm.argname63", T_STR, "openbsm argument name 63" },
  { "openbsm.arg64", T_UINT, "openbsm argument 64" },
  { "openbsm.argname64", T_STR, "openbsm argument name 64" },
  { "openbsm.arg65", T_UINT, "openbsm argument 65" },
  { "openbsm.argname65", T_STR, "openbsm argument name 65" },
  { "openbsm.arg66", T_UINT, "openbsm argument 66" },
  { "openbsm.argname66", T_STR, "openbsm argument name 66" },
  { "openbsm.arg67", T_UINT, "openbsm argument 67" },
  { "openbsm.argname67", T_STR, "openbsm argument name 67" },
  { "openbsm.arg68", T_UINT, "openbsm argument 68" },
  { "openbsm.argname68", T_STR, "openbsm argument name 68" },
  { "openbsm.arg69", T_UINT, "openbsm argument 69" },
  { "openbsm.argname69", T_STR, "openbsm argument name 69" },
  { "openbsm.arg70", T_UINT, "openbsm argument 70" },
  { "openbsm.argname70", T_STR, "openbsm argument name 70" },
  { "openbsm.arg71", T_UINT, "openbsm argument 71" },
  { "openbsm.argname71", T_STR, "openbsm argument name 71" },
  { "openbsm.arg72", T_UINT, "openbsm argument 72" },
  { "openbsm.argname72", T_STR, "openbsm argument name 72" },
  { "openbsm.arg73", T_UINT, "openbsm argument 73" },
  { "openbsm.argname73", T_STR, "openbsm argument name 73" },
  { "openbsm.arg74", T_UINT, "openbsm argument 74" },
  { "openbsm.argname74", T_STR, "openbsm argument name 74" },
  { "openbsm.arg75", T_UINT, "openbsm argument 75" },
  { "openbsm.argname75", T_STR, "openbsm argument name 75" },
  { "openbsm.arg76", T_UINT, "openbsm argument 76" },
  { "openbsm.argname76", T_STR, "openbsm argument name 76" },
  { "openbsm.arg77", T_UINT, "openbsm argument 77" },
  { "openbsm.argname77", T_STR, "openbsm argument name 77" },
  { "openbsm.arg78", T_UINT, "openbsm argument 78" },
  { "openbsm.argname78", T_STR, "openbsm argument name 78" },
  { "openbsm.arg79", T_UINT, "openbsm argument 79" },
  { "openbsm.argname79", T_STR, "openbsm argument name 79" },
  { "openbsm.arg80", T_UINT, "openbsm argument 80" },
  { "openbsm.argname80", T_STR, "openbsm argument name 80" },
  { "openbsm.arg81", T_UINT, "openbsm argument 81" },
  { "openbsm.argname81", T_STR, "openbsm argument name 81" },
  { "openbsm.arg82", T_UINT, "openbsm argument 82" },
  { "openbsm.argname82", T_STR, "openbsm argument name 82" },
  { "openbsm.arg83", T_UINT, "openbsm argument 83" },
  { "openbsm.argname83", T_STR, "openbsm argument name 83" },
  { "openbsm.arg84", T_UINT, "openbsm argument 84" },
  { "openbsm.argname84", T_STR, "openbsm argument name 84" },
  { "openbsm.arg85", T_UINT, "openbsm argument 85" },
  { "openbsm.argname85", T_STR, "openbsm argument name 85" },
  { "openbsm.arg86", T_UINT, "openbsm argument 86" },
  { "openbsm.argname86", T_STR, "openbsm argument name 86" },
  { "openbsm.arg87", T_UINT, "openbsm argument 87" },
  { "openbsm.argname87", T_STR, "openbsm argument name 87" },
  { "openbsm.arg88", T_UINT, "openbsm argument 88" },
  { "openbsm.argname88", T_STR, "openbsm argument name 88" },
  { "openbsm.arg89", T_UINT, "openbsm argument 89" },
  { "openbsm.argname89", T_STR, "openbsm argument name 89" },
  { "openbsm.arg90", T_UINT, "openbsm argument 90" },
  { "openbsm.argname90", T_STR, "openbsm argument name 90" },
  { "openbsm.arg91", T_UINT, "openbsm argument 91" },
  { "openbsm.argname91", T_STR, "openbsm argument name 91" },
  { "openbsm.arg92", T_UINT, "openbsm argument 92" },
  { "openbsm.argname92", T_STR, "openbsm argument name 92" },
  { "openbsm.arg93", T_UINT, "openbsm argument 93" },
  { "openbsm.argname93", T_STR, "openbsm argument name 93" },
  { "openbsm.arg94", T_UINT, "openbsm argument 94" },
  { "openbsm.argname94", T_STR, "openbsm argument name 94" },
  { "openbsm.arg95", T_UINT, "openbsm argument 95" },
  { "openbsm.argname95", T_STR, "openbsm argument name 95" },
  { "openbsm.arg96", T_UINT, "openbsm argument 96" },
  { "openbsm.argname96", T_STR, "openbsm argument name 96" },
  { "openbsm.arg97", T_UINT, "openbsm argument 97" },
  { "openbsm.argname97", T_STR, "openbsm argument name 97" },
  { "openbsm.arg98", T_UINT, "openbsm argument 98" },
  { "openbsm.argname98", T_STR, "openbsm argument name 98" },
  { "openbsm.arg99", T_UINT, "openbsm argument 99" },
  { "openbsm.argname99", T_STR, "openbsm argument name 99" },
  { "openbsm.arg100", T_UINT, "openbsm argument 100" },
  { "openbsm.argname100", T_STR, "openbsm argument name 100" },
  { "openbsm.arg101", T_UINT, "openbsm argument 101" },
  { "openbsm.argname101", T_STR, "openbsm argument name 101" },
  { "openbsm.arg102", T_UINT, "openbsm argument 102" },
  { "openbsm.argname102", T_STR, "openbsm argument name 102" },
  { "openbsm.arg103", T_UINT, "openbsm argument 103" },
  { "openbsm.argname103", T_STR, "openbsm argument name 103" },
  { "openbsm.arg104", T_UINT, "openbsm argument 104" },
  { "openbsm.argname104", T_STR, "openbsm argument name 104" },
  { "openbsm.arg105", T_UINT, "openbsm argument 105" },
  { "openbsm.argname105", T_STR, "openbsm argument name 105" },
  { "openbsm.arg106", T_UINT, "openbsm argument 106" },
  { "openbsm.argname106", T_STR, "openbsm argument name 106" },
  { "openbsm.arg107", T_UINT, "openbsm argument 107" },
  { "openbsm.argname107", T_STR, "openbsm argument name 107" },
  { "openbsm.arg108", T_UINT, "openbsm argument 108" },
  { "openbsm.argname108", T_STR, "openbsm argument name 108" },
  { "openbsm.arg109", T_UINT, "openbsm argument 109" },
  { "openbsm.argname109", T_STR, "openbsm argument name 109" },
  { "openbsm.arg110", T_UINT, "openbsm argument 110" },
  { "openbsm.argname110", T_STR, "openbsm argument name 110" },
  { "openbsm.arg111", T_UINT, "openbsm argument 111" },
  { "openbsm.argname111", T_STR, "openbsm argument name 111" },
  { "openbsm.arg112", T_UINT, "openbsm argument 112" },
  { "openbsm.argname112", T_STR, "openbsm argument name 112" },
  { "openbsm.arg113", T_UINT, "openbsm argument 113" },
  { "openbsm.argname113", T_STR, "openbsm argument name 113" },
  { "openbsm.arg114", T_UINT, "openbsm argument 114" },
  { "openbsm.argname114", T_STR, "openbsm argument name 114" },
  { "openbsm.arg115", T_UINT, "openbsm argument 115" },
  { "openbsm.argname115", T_STR, "openbsm argument name 115" },
  { "openbsm.arg116", T_UINT, "openbsm argument 116" },
  { "openbsm.argname116", T_STR, "openbsm argument name 116" },
  { "openbsm.arg117", T_UINT, "openbsm argument 117" },
  { "openbsm.argname117", T_STR, "openbsm argument name 117" },
  { "openbsm.arg118", T_UINT, "openbsm argument 118" },
  { "openbsm.argname118", T_STR, "openbsm argument name 118" },
  { "openbsm.arg119", T_UINT, "openbsm argument 119" },
  { "openbsm.argname119", T_STR, "openbsm argument name 119" },
  { "openbsm.arg120", T_UINT, "openbsm argument 120" },
  { "openbsm.argname120", T_STR, "openbsm argument name 120" },
  { "openbsm.arg121", T_UINT, "openbsm argument 121" },
  { "openbsm.argname121", T_STR, "openbsm argument name 121" },
  { "openbsm.arg122", T_UINT, "openbsm argument 122" },
  { "openbsm.argname122", T_STR, "openbsm argument name 122" },
  { "openbsm.arg123", T_UINT, "openbsm argument 123" },
  { "openbsm.argname123", T_STR, "openbsm argument name 123" },
  { "openbsm.arg124", T_UINT, "openbsm argument 124" },
  { "openbsm.argname124", T_STR, "openbsm argument name 124" },
  { "openbsm.arg125", T_UINT, "openbsm argument 125" },
  { "openbsm.argname125", T_STR, "openbsm argument name 125" },
  { "openbsm.arg126", T_UINT, "openbsm argument 126" },
  { "openbsm.argname126", T_STR, "openbsm argument name 126" },
  { "openbsm.arg127", T_UINT, "openbsm argument 127" },
  { "openbsm.argname127", T_STR, "openbsm argument name 127" },
  { "openbsm.arg128", T_UINT, "openbsm argument 128" },
  { "openbsm.argname128", T_STR, "openbsm argument name 128" },
#define F_OPENBSM_ARG_END (F_OPENBSM_ARG_START+128)
#define F_OPENBSM_EXECARG_START F_OPENBSM_ARG_END
  { "bsm.execarg_num", T_UINT, "bsm exec argument number" },
#define F_OPENBSM_EXECARG_NUM 0
  { "bsm.execarg1", T_STR, "openbsm exec argument 1" },
  { "bsm.execarg2", T_STR, "openbsm exec argument 2" },
  { "bsm.execarg3", T_STR, "openbsm exec argument 3" },
  { "bsm.execarg4", T_STR, "openbsm exec argument 4" },
  { "bsm.execarg5", T_STR, "openbsm exec argument 5" },
  { "bsm.execarg6", T_STR, "openbsm exec argument 6" },
  { "bsm.execarg7", T_STR, "openbsm exec argument 7" },
  { "bsm.execarg8", T_STR, "openbsm exec argument 8" },
  { "bsm.execarg9", T_STR, "openbsm exec argument 9" },
  { "bsm.execarg10", T_STR, "openbsm exec argument 10" },
  { "bsm.execarg11", T_STR, "openbsm exec argument 11" },
  { "bsm.execarg12", T_STR, "openbsm exec argument 12" },
  { "bsm.execarg13", T_STR, "openbsm exec argument 13" },
  { "bsm.execarg14", T_STR, "openbsm exec argument 14" },
  { "bsm.execarg15", T_STR, "openbsm exec argument 15" },
  { "bsm.execarg16", T_STR, "openbsm exec argument 16" },
  { "bsm.execarg17", T_STR, "openbsm exec argument 17" },
  { "bsm.execarg18", T_STR, "openbsm exec argument 18" },
  { "bsm.execarg19", T_STR, "openbsm exec argument 19" },
  { "bsm.execarg20", T_STR, "openbsm exec argument 20" },
  { "bsm.execarg21", T_STR, "openbsm exec argument 21" },
  { "bsm.execarg22", T_STR, "openbsm exec argument 22" },
  { "bsm.execarg23", T_STR, "openbsm exec argument 23" },
  { "bsm.execarg24", T_STR, "openbsm exec argument 24" },
  { "bsm.execarg25", T_STR, "openbsm exec argument 25" },
  { "bsm.execarg26", T_STR, "openbsm exec argument 26" },
  { "bsm.execarg27", T_STR, "openbsm exec argument 27" },
  { "bsm.execarg28", T_STR, "openbsm exec argument 28" },
  { "bsm.execarg29", T_STR, "openbsm exec argument 29" },
  { "bsm.execarg30", T_STR, "openbsm exec argument 30" },
  { "bsm.execarg31", T_STR, "openbsm exec argument 31" },
  { "bsm.execarg32", T_STR, "openbsm exec argument 32" },
  { "bsm.execarg33", T_STR, "openbsm exec argument 33" },
  { "bsm.execarg34", T_STR, "openbsm exec argument 34" },
  { "bsm.execarg35", T_STR, "openbsm exec argument 35" },
  { "bsm.execarg36", T_STR, "openbsm exec argument 36" },
  { "bsm.execarg37", T_STR, "openbsm exec argument 37" },
  { "bsm.execarg38", T_STR, "openbsm exec argument 38" },
  { "bsm.execarg39", T_STR, "openbsm exec argument 39" },
  { "bsm.execarg40", T_STR, "openbsm exec argument 40" },
  { "bsm.execarg41", T_STR, "openbsm exec argument 41" },
  { "bsm.execarg42", T_STR, "openbsm exec argument 42" },
  { "bsm.execarg43", T_STR, "openbsm exec argument 43" },
  { "bsm.execarg44", T_STR, "openbsm exec argument 44" },
  { "bsm.execarg45", T_STR, "openbsm exec argument 45" },
  { "bsm.execarg46", T_STR, "openbsm exec argument 46" },
  { "bsm.execarg47", T_STR, "openbsm exec argument 47" },
  { "bsm.execarg48", T_STR, "openbsm exec argument 48" },
  { "bsm.execarg49", T_STR, "openbsm exec argument 49" },
  { "bsm.execarg50", T_STR, "openbsm exec argument 50" },
  { "bsm.execarg51", T_STR, "openbsm exec argument 51" },
  { "bsm.execarg52", T_STR, "openbsm exec argument 52" },
  { "bsm.execarg53", T_STR, "openbsm exec argument 53" },
  { "bsm.execarg54", T_STR, "openbsm exec argument 54" },
  { "bsm.execarg55", T_STR, "openbsm exec argument 55" },
  { "bsm.execarg56", T_STR, "openbsm exec argument 56" },
  { "bsm.execarg57", T_STR, "openbsm exec argument 57" },
  { "bsm.execarg58", T_STR, "openbsm exec argument 58" },
  { "bsm.execarg59", T_STR, "openbsm exec argument 59" },
  { "bsm.execarg60", T_STR, "openbsm exec argument 60" },
  { "bsm.execarg61", T_STR, "openbsm exec argument 61" },
  { "bsm.execarg62", T_STR, "openbsm exec argument 62" },
  { "bsm.execarg63", T_STR, "openbsm exec argument 63" },
  { "bsm.execarg64", T_STR, "openbsm exec argument 64" },
  { "bsm.execarg65", T_STR, "openbsm exec argument 65" },
  { "bsm.execarg66", T_STR, "openbsm exec argument 66" },
  { "bsm.execarg67", T_STR, "openbsm exec argument 67" },
  { "bsm.execarg68", T_STR, "openbsm exec argument 68" },
  { "bsm.execarg69", T_STR, "openbsm exec argument 69" },
  { "bsm.execarg70", T_STR, "openbsm exec argument 70" },
  { "bsm.execarg71", T_STR, "openbsm exec argument 71" },
  { "bsm.execarg72", T_STR, "openbsm exec argument 72" },
  { "bsm.execarg73", T_STR, "openbsm exec argument 73" },
  { "bsm.execarg74", T_STR, "openbsm exec argument 74" },
  { "bsm.execarg75", T_STR, "openbsm exec argument 75" },
  { "bsm.execarg76", T_STR, "openbsm exec argument 76" },
  { "bsm.execarg77", T_STR, "openbsm exec argument 77" },
  { "bsm.execarg78", T_STR, "openbsm exec argument 78" },
  { "bsm.execarg79", T_STR, "openbsm exec argument 79" },
  { "bsm.execarg80", T_STR, "openbsm exec argument 80" },
  { "bsm.execarg81", T_STR, "openbsm exec argument 81" },
  { "bsm.execarg82", T_STR, "openbsm exec argument 82" },
  { "bsm.execarg83", T_STR, "openbsm exec argument 83" },
  { "bsm.execarg84", T_STR, "openbsm exec argument 84" },
  { "bsm.execarg85", T_STR, "openbsm exec argument 85" },
  { "bsm.execarg86", T_STR, "openbsm exec argument 86" },
  { "bsm.execarg87", T_STR, "openbsm exec argument 87" },
  { "bsm.execarg88", T_STR, "openbsm exec argument 88" },
  { "bsm.execarg89", T_STR, "openbsm exec argument 89" },
  { "bsm.execarg90", T_STR, "openbsm exec argument 90" },
  { "bsm.execarg91", T_STR, "openbsm exec argument 91" },
  { "bsm.execarg92", T_STR, "openbsm exec argument 92" },
  { "bsm.execarg93", T_STR, "openbsm exec argument 93" },
  { "bsm.execarg94", T_STR, "openbsm exec argument 94" },
  { "bsm.execarg95", T_STR, "openbsm exec argument 95" },
  { "bsm.execarg96", T_STR, "openbsm exec argument 96" },
  { "bsm.execarg97", T_STR, "openbsm exec argument 97" },
  { "bsm.execarg98", T_STR, "openbsm exec argument 98" },
  { "bsm.execarg99", T_STR, "openbsm exec argument 99" },
  { "bsm.execarg100", T_STR, "openbsm exec argument 100" },
  { "bsm.execarg101", T_STR, "openbsm exec argument 101" },
  { "bsm.execarg102", T_STR, "openbsm exec argument 102" },
  { "bsm.execarg103", T_STR, "openbsm exec argument 103" },
  { "bsm.execarg104", T_STR, "openbsm exec argument 104" },
  { "bsm.execarg105", T_STR, "openbsm exec argument 105" },
  { "bsm.execarg106", T_STR, "openbsm exec argument 106" },
  { "bsm.execarg107", T_STR, "openbsm exec argument 107" },
  { "bsm.execarg108", T_STR, "openbsm exec argument 108" },
  { "bsm.execarg109", T_STR, "openbsm exec argument 109" },
  { "bsm.execarg110", T_STR, "openbsm exec argument 110" },
  { "bsm.execarg111", T_STR, "openbsm exec argument 111" },
  { "bsm.execarg112", T_STR, "openbsm exec argument 112" },
  { "bsm.execarg113", T_STR, "openbsm exec argument 113" },
  { "bsm.execarg114", T_STR, "openbsm exec argument 114" },
  { "bsm.execarg115", T_STR, "openbsm exec argument 115" },
  { "bsm.execarg116", T_STR, "openbsm exec argument 116" },
  { "bsm.execarg117", T_STR, "openbsm exec argument 117" },
  { "bsm.execarg118", T_STR, "openbsm exec argument 118" },
  { "bsm.execarg119", T_STR, "openbsm exec argument 119" },
  { "bsm.execarg120", T_STR, "openbsm exec argument 120" },
  { "bsm.execarg121", T_STR, "openbsm exec argument 121" },
  { "bsm.execarg122", T_STR, "openbsm exec argument 122" },
  { "bsm.execarg123", T_STR, "openbsm exec argument 123" },
  { "bsm.execarg124", T_STR, "openbsm exec argument 124" },
  { "bsm.execarg125", T_STR, "openbsm exec argument 125" },
  { "bsm.execarg126", T_STR, "openbsm exec argument 126" },
  { "bsm.execarg127", T_STR, "openbsm exec argument 127" },
  { "bsm.execarg128", T_STR, "openbsm exec argument 128" },
#define F_OPENBSM_EXECARG_END (F_OPENBSM_EXECARG_START+129)
#define F_OPENBSM_EXECENV_START F_OPENBSM_EXECARG_END
  { "bsm.execenv_num", T_UINT, "bsm exec number of environment variables" },
#define F_OPENBSM_EXECENV_NUM 0
  { "bsm.execenv1", T_STR, "openbsm exec environment variable 1" },
  { "bsm.execenv2", T_STR, "openbsm exec environment variable 2" },
  { "bsm.execenv3", T_STR, "openbsm exec environment variable 3" },
  { "bsm.execenv4", T_STR, "openbsm exec environment variable 4" },
  { "bsm.execenv5", T_STR, "openbsm exec environment variable 5" },
  { "bsm.execenv6", T_STR, "openbsm exec environment variable 6" },
  { "bsm.execenv7", T_STR, "openbsm exec environment variable 7" },
  { "bsm.execenv8", T_STR, "openbsm exec environment variable 8" },
  { "bsm.execenv9", T_STR, "openbsm exec environment variable 9" },
  { "bsm.execenv10", T_STR, "openbsm exec environment variable 10" },
  { "bsm.execenv11", T_STR, "openbsm exec environment variable 11" },
  { "bsm.execenv12", T_STR, "openbsm exec environment variable 12" },
  { "bsm.execenv13", T_STR, "openbsm exec environment variable 13" },
  { "bsm.execenv14", T_STR, "openbsm exec environment variable 14" },
  { "bsm.execenv15", T_STR, "openbsm exec environment variable 15" },
  { "bsm.execenv16", T_STR, "openbsm exec environment variable 16" },
  { "bsm.execenv17", T_STR, "openbsm exec environment variable 17" },
  { "bsm.execenv18", T_STR, "openbsm exec environment variable 18" },
  { "bsm.execenv19", T_STR, "openbsm exec environment variable 19" },
  { "bsm.execenv20", T_STR, "openbsm exec environment variable 20" },
  { "bsm.execenv21", T_STR, "openbsm exec environment variable 21" },
  { "bsm.execenv22", T_STR, "openbsm exec environment variable 22" },
  { "bsm.execenv23", T_STR, "openbsm exec environment variable 23" },
  { "bsm.execenv24", T_STR, "openbsm exec environment variable 24" },
  { "bsm.execenv25", T_STR, "openbsm exec environment variable 25" },
  { "bsm.execenv26", T_STR, "openbsm exec environment variable 26" },
  { "bsm.execenv27", T_STR, "openbsm exec environment variable 27" },
  { "bsm.execenv28", T_STR, "openbsm exec environment variable 28" },
  { "bsm.execenv29", T_STR, "openbsm exec environment variable 29" },
  { "bsm.execenv30", T_STR, "openbsm exec environment variable 30" },
  { "bsm.execenv31", T_STR, "openbsm exec environment variable 31" },
  { "bsm.execenv32", T_STR, "openbsm exec environment variable 32" },
  { "bsm.execenv33", T_STR, "openbsm exec environment variable 33" },
  { "bsm.execenv34", T_STR, "openbsm exec environment variable 34" },
  { "bsm.execenv35", T_STR, "openbsm exec environment variable 35" },
  { "bsm.execenv36", T_STR, "openbsm exec environment variable 36" },
  { "bsm.execenv37", T_STR, "openbsm exec environment variable 37" },
  { "bsm.execenv38", T_STR, "openbsm exec environment variable 38" },
  { "bsm.execenv39", T_STR, "openbsm exec environment variable 39" },
  { "bsm.execenv40", T_STR, "openbsm exec environment variable 40" },
  { "bsm.execenv41", T_STR, "openbsm exec environment variable 41" },
  { "bsm.execenv42", T_STR, "openbsm exec environment variable 42" },
  { "bsm.execenv43", T_STR, "openbsm exec environment variable 43" },
  { "bsm.execenv44", T_STR, "openbsm exec environment variable 44" },
  { "bsm.execenv45", T_STR, "openbsm exec environment variable 45" },
  { "bsm.execenv46", T_STR, "openbsm exec environment variable 46" },
  { "bsm.execenv47", T_STR, "openbsm exec environment variable 47" },
  { "bsm.execenv48", T_STR, "openbsm exec environment variable 48" },
  { "bsm.execenv49", T_STR, "openbsm exec environment variable 49" },
  { "bsm.execenv50", T_STR, "openbsm exec environment variable 50" },
  { "bsm.execenv51", T_STR, "openbsm exec environment variable 51" },
  { "bsm.execenv52", T_STR, "openbsm exec environment variable 52" },
  { "bsm.execenv53", T_STR, "openbsm exec environment variable 53" },
  { "bsm.execenv54", T_STR, "openbsm exec environment variable 54" },
  { "bsm.execenv55", T_STR, "openbsm exec environment variable 55" },
  { "bsm.execenv56", T_STR, "openbsm exec environment variable 56" },
  { "bsm.execenv57", T_STR, "openbsm exec environment variable 57" },
  { "bsm.execenv58", T_STR, "openbsm exec environment variable 58" },
  { "bsm.execenv59", T_STR, "openbsm exec environment variable 59" },
  { "bsm.execenv60", T_STR, "openbsm exec environment variable 60" },
  { "bsm.execenv61", T_STR, "openbsm exec environment variable 61" },
  { "bsm.execenv62", T_STR, "openbsm exec environment variable 62" },
  { "bsm.execenv63", T_STR, "openbsm exec environment variable 63" },
  { "bsm.execenv64", T_STR, "openbsm exec environment variable 64" },
  { "bsm.execenv65", T_STR, "openbsm exec environment variable 65" },
  { "bsm.execenv66", T_STR, "openbsm exec environment variable 66" },
  { "bsm.execenv67", T_STR, "openbsm exec environment variable 67" },
  { "bsm.execenv68", T_STR, "openbsm exec environment variable 68" },
  { "bsm.execenv69", T_STR, "openbsm exec environment variable 69" },
  { "bsm.execenv70", T_STR, "openbsm exec environment variable 70" },
  { "bsm.execenv71", T_STR, "openbsm exec environment variable 71" },
  { "bsm.execenv72", T_STR, "openbsm exec environment variable 72" },
  { "bsm.execenv73", T_STR, "openbsm exec environment variable 73" },
  { "bsm.execenv74", T_STR, "openbsm exec environment variable 74" },
  { "bsm.execenv75", T_STR, "openbsm exec environment variable 75" },
  { "bsm.execenv76", T_STR, "openbsm exec environment variable 76" },
  { "bsm.execenv77", T_STR, "openbsm exec environment variable 77" },
  { "bsm.execenv78", T_STR, "openbsm exec environment variable 78" },
  { "bsm.execenv79", T_STR, "openbsm exec environment variable 79" },
  { "bsm.execenv80", T_STR, "openbsm exec environment variable 80" },
  { "bsm.execenv81", T_STR, "openbsm exec environment variable 81" },
  { "bsm.execenv82", T_STR, "openbsm exec environment variable 82" },
  { "bsm.execenv83", T_STR, "openbsm exec environment variable 83" },
  { "bsm.execenv84", T_STR, "openbsm exec environment variable 84" },
  { "bsm.execenv85", T_STR, "openbsm exec environment variable 85" },
  { "bsm.execenv86", T_STR, "openbsm exec environment variable 86" },
  { "bsm.execenv87", T_STR, "openbsm exec environment variable 87" },
  { "bsm.execenv88", T_STR, "openbsm exec environment variable 88" },
  { "bsm.execenv89", T_STR, "openbsm exec environment variable 89" },
  { "bsm.execenv90", T_STR, "openbsm exec environment variable 90" },
  { "bsm.execenv91", T_STR, "openbsm exec environment variable 91" },
  { "bsm.execenv92", T_STR, "openbsm exec environment variable 92" },
  { "bsm.execenv93", T_STR, "openbsm exec environment variable 93" },
  { "bsm.execenv94", T_STR, "openbsm exec environment variable 94" },
  { "bsm.execenv95", T_STR, "openbsm exec environment variable 95" },
  { "bsm.execenv96", T_STR, "openbsm exec environment variable 96" },
  { "bsm.execenv97", T_STR, "openbsm exec environment variable 97" },
  { "bsm.execenv98", T_STR, "openbsm exec environment variable 98" },
  { "bsm.execenv99", T_STR, "openbsm exec environment variable 99" },
  { "bsm.execenv100", T_STR, "openbsm exec environment variable 100" },
  { "bsm.execenv101", T_STR, "openbsm exec environment variable 101" },
  { "bsm.execenv102", T_STR, "openbsm exec environment variable 102" },
  { "bsm.execenv103", T_STR, "openbsm exec environment variable 103" },
  { "bsm.execenv104", T_STR, "openbsm exec environment variable 104" },
  { "bsm.execenv105", T_STR, "openbsm exec environment variable 105" },
  { "bsm.execenv106", T_STR, "openbsm exec environment variable 106" },
  { "bsm.execenv107", T_STR, "openbsm exec environment variable 107" },
  { "bsm.execenv108", T_STR, "openbsm exec environment variable 108" },
  { "bsm.execenv109", T_STR, "openbsm exec environment variable 109" },
  { "bsm.execenv110", T_STR, "openbsm exec environment variable 110" },
  { "bsm.execenv111", T_STR, "openbsm exec environment variable 111" },
  { "bsm.execenv112", T_STR, "openbsm exec environment variable 112" },
  { "bsm.execenv113", T_STR, "openbsm exec environment variable 113" },
  { "bsm.execenv114", T_STR, "openbsm exec environment variable 114" },
  { "bsm.execenv115", T_STR, "openbsm exec environment variable 115" },
  { "bsm.execenv116", T_STR, "openbsm exec environment variable 116" },
  { "bsm.execenv117", T_STR, "openbsm exec environment variable 117" },
  { "bsm.execenv118", T_STR, "openbsm exec environment variable 118" },
  { "bsm.execenv119", T_STR, "openbsm exec environment variable 119" },
  { "bsm.execenv120", T_STR, "openbsm exec environment variable 120" },
  { "bsm.execenv121", T_STR, "openbsm exec environment variable 121" },
  { "bsm.execenv122", T_STR, "openbsm exec environment variable 122" },
  { "bsm.execenv123", T_STR, "openbsm exec environment variable 123" },
  { "bsm.execenv124", T_STR, "openbsm exec environment variable 124" },
  { "bsm.execenv125", T_STR, "openbsm exec environment variable 125" },
  { "bsm.execenv126", T_STR, "openbsm exec environment variable 126" },
  { "bsm.execenv127", T_STR, "openbsm exec environment variable 127" },
  { "bsm.execenv128", T_STR, "openbsm exec environment variable 128" },
#define F_OPENBSM_EXECENV_END (F_OPENBSM_EXECENV_START+129)
#define F_OPENBSM_NEWGROUPS_START F_OPENBSM_EXECENV_END
  { "bsm.newgroups_num", T_UINT, "bsm number of new groups" },
#define F_OPENBSM_NEWGROUPS_NUM 0
  { "bsm.newgroup1", T_UINT, "openbsm new group 1" },
  { "bsm.newgroup2", T_UINT, "openbsm new group 2" },
  { "bsm.newgroup3", T_UINT, "openbsm new group 3" },
  { "bsm.newgroup4", T_UINT, "openbsm new group 4" },
  { "bsm.newgroup5", T_UINT, "openbsm new group 5" },
  { "bsm.newgroup6", T_UINT, "openbsm new group 6" },
  { "bsm.newgroup7", T_UINT, "openbsm new group 7" },
  { "bsm.newgroup8", T_UINT, "openbsm new group 8" },
  { "bsm.newgroup9", T_UINT, "openbsm new group 9" },
  { "bsm.newgroup10", T_UINT, "openbsm new group 10" },
  { "bsm.newgroup11", T_UINT, "openbsm new group 11" },
  { "bsm.newgroup12", T_UINT, "openbsm new group 12" },
  { "bsm.newgroup13", T_UINT, "openbsm new group 13" },
  { "bsm.newgroup14", T_UINT, "openbsm new group 14" },
  { "bsm.newgroup15", T_UINT, "openbsm new group 15" },
  { "bsm.newgroup16", T_UINT, "openbsm new group 16" },
#define F_OPENBSM_NEWGROUPS_END (F_OPENBSM_NEWGROUPS_START+17)
#define OPENBSM_FIELDS F_OPENBSM_NEWGROUPS_END
