// Generated automatically by gen_mod_openbsm.c: do not touch!
// Copyright, license: see file gen_mod_openbsm.c.
#define OPENBSM_MAX_ARGS 128
#define OPENBSM_MAX_ENV 128
#define OPENBSM_MAX_GROUPS 16
#define F_OPENBSM_ARG_START F_OPENBSM_REGULAR_END
  { "openbsm.arg1", &t_uint, "openbsm argument 1" },
  { "openbsm.argname1", &t_str, "openbsm argument name 1" },
  { "openbsm.arg2", &t_uint, "openbsm argument 2" },
  { "openbsm.argname2", &t_str, "openbsm argument name 2" },
  { "openbsm.arg3", &t_uint, "openbsm argument 3" },
  { "openbsm.argname3", &t_str, "openbsm argument name 3" },
  { "openbsm.arg4", &t_uint, "openbsm argument 4" },
  { "openbsm.argname4", &t_str, "openbsm argument name 4" },
  { "openbsm.arg5", &t_uint, "openbsm argument 5" },
  { "openbsm.argname5", &t_str, "openbsm argument name 5" },
  { "openbsm.arg6", &t_uint, "openbsm argument 6" },
  { "openbsm.argname6", &t_str, "openbsm argument name 6" },
  { "openbsm.arg7", &t_uint, "openbsm argument 7" },
  { "openbsm.argname7", &t_str, "openbsm argument name 7" },
  { "openbsm.arg8", &t_uint, "openbsm argument 8" },
  { "openbsm.argname8", &t_str, "openbsm argument name 8" },
  { "openbsm.arg9", &t_uint, "openbsm argument 9" },
  { "openbsm.argname9", &t_str, "openbsm argument name 9" },
  { "openbsm.arg10", &t_uint, "openbsm argument 10" },
  { "openbsm.argname10", &t_str, "openbsm argument name 10" },
  { "openbsm.arg11", &t_uint, "openbsm argument 11" },
  { "openbsm.argname11", &t_str, "openbsm argument name 11" },
  { "openbsm.arg12", &t_uint, "openbsm argument 12" },
  { "openbsm.argname12", &t_str, "openbsm argument name 12" },
  { "openbsm.arg13", &t_uint, "openbsm argument 13" },
  { "openbsm.argname13", &t_str, "openbsm argument name 13" },
  { "openbsm.arg14", &t_uint, "openbsm argument 14" },
  { "openbsm.argname14", &t_str, "openbsm argument name 14" },
  { "openbsm.arg15", &t_uint, "openbsm argument 15" },
  { "openbsm.argname15", &t_str, "openbsm argument name 15" },
  { "openbsm.arg16", &t_uint, "openbsm argument 16" },
  { "openbsm.argname16", &t_str, "openbsm argument name 16" },
  { "openbsm.arg17", &t_uint, "openbsm argument 17" },
  { "openbsm.argname17", &t_str, "openbsm argument name 17" },
  { "openbsm.arg18", &t_uint, "openbsm argument 18" },
  { "openbsm.argname18", &t_str, "openbsm argument name 18" },
  { "openbsm.arg19", &t_uint, "openbsm argument 19" },
  { "openbsm.argname19", &t_str, "openbsm argument name 19" },
  { "openbsm.arg20", &t_uint, "openbsm argument 20" },
  { "openbsm.argname20", &t_str, "openbsm argument name 20" },
  { "openbsm.arg21", &t_uint, "openbsm argument 21" },
  { "openbsm.argname21", &t_str, "openbsm argument name 21" },
  { "openbsm.arg22", &t_uint, "openbsm argument 22" },
  { "openbsm.argname22", &t_str, "openbsm argument name 22" },
  { "openbsm.arg23", &t_uint, "openbsm argument 23" },
  { "openbsm.argname23", &t_str, "openbsm argument name 23" },
  { "openbsm.arg24", &t_uint, "openbsm argument 24" },
  { "openbsm.argname24", &t_str, "openbsm argument name 24" },
  { "openbsm.arg25", &t_uint, "openbsm argument 25" },
  { "openbsm.argname25", &t_str, "openbsm argument name 25" },
  { "openbsm.arg26", &t_uint, "openbsm argument 26" },
  { "openbsm.argname26", &t_str, "openbsm argument name 26" },
  { "openbsm.arg27", &t_uint, "openbsm argument 27" },
  { "openbsm.argname27", &t_str, "openbsm argument name 27" },
  { "openbsm.arg28", &t_uint, "openbsm argument 28" },
  { "openbsm.argname28", &t_str, "openbsm argument name 28" },
  { "openbsm.arg29", &t_uint, "openbsm argument 29" },
  { "openbsm.argname29", &t_str, "openbsm argument name 29" },
  { "openbsm.arg30", &t_uint, "openbsm argument 30" },
  { "openbsm.argname30", &t_str, "openbsm argument name 30" },
  { "openbsm.arg31", &t_uint, "openbsm argument 31" },
  { "openbsm.argname31", &t_str, "openbsm argument name 31" },
  { "openbsm.arg32", &t_uint, "openbsm argument 32" },
  { "openbsm.argname32", &t_str, "openbsm argument name 32" },
  { "openbsm.arg33", &t_uint, "openbsm argument 33" },
  { "openbsm.argname33", &t_str, "openbsm argument name 33" },
  { "openbsm.arg34", &t_uint, "openbsm argument 34" },
  { "openbsm.argname34", &t_str, "openbsm argument name 34" },
  { "openbsm.arg35", &t_uint, "openbsm argument 35" },
  { "openbsm.argname35", &t_str, "openbsm argument name 35" },
  { "openbsm.arg36", &t_uint, "openbsm argument 36" },
  { "openbsm.argname36", &t_str, "openbsm argument name 36" },
  { "openbsm.arg37", &t_uint, "openbsm argument 37" },
  { "openbsm.argname37", &t_str, "openbsm argument name 37" },
  { "openbsm.arg38", &t_uint, "openbsm argument 38" },
  { "openbsm.argname38", &t_str, "openbsm argument name 38" },
  { "openbsm.arg39", &t_uint, "openbsm argument 39" },
  { "openbsm.argname39", &t_str, "openbsm argument name 39" },
  { "openbsm.arg40", &t_uint, "openbsm argument 40" },
  { "openbsm.argname40", &t_str, "openbsm argument name 40" },
  { "openbsm.arg41", &t_uint, "openbsm argument 41" },
  { "openbsm.argname41", &t_str, "openbsm argument name 41" },
  { "openbsm.arg42", &t_uint, "openbsm argument 42" },
  { "openbsm.argname42", &t_str, "openbsm argument name 42" },
  { "openbsm.arg43", &t_uint, "openbsm argument 43" },
  { "openbsm.argname43", &t_str, "openbsm argument name 43" },
  { "openbsm.arg44", &t_uint, "openbsm argument 44" },
  { "openbsm.argname44", &t_str, "openbsm argument name 44" },
  { "openbsm.arg45", &t_uint, "openbsm argument 45" },
  { "openbsm.argname45", &t_str, "openbsm argument name 45" },
  { "openbsm.arg46", &t_uint, "openbsm argument 46" },
  { "openbsm.argname46", &t_str, "openbsm argument name 46" },
  { "openbsm.arg47", &t_uint, "openbsm argument 47" },
  { "openbsm.argname47", &t_str, "openbsm argument name 47" },
  { "openbsm.arg48", &t_uint, "openbsm argument 48" },
  { "openbsm.argname48", &t_str, "openbsm argument name 48" },
  { "openbsm.arg49", &t_uint, "openbsm argument 49" },
  { "openbsm.argname49", &t_str, "openbsm argument name 49" },
  { "openbsm.arg50", &t_uint, "openbsm argument 50" },
  { "openbsm.argname50", &t_str, "openbsm argument name 50" },
  { "openbsm.arg51", &t_uint, "openbsm argument 51" },
  { "openbsm.argname51", &t_str, "openbsm argument name 51" },
  { "openbsm.arg52", &t_uint, "openbsm argument 52" },
  { "openbsm.argname52", &t_str, "openbsm argument name 52" },
  { "openbsm.arg53", &t_uint, "openbsm argument 53" },
  { "openbsm.argname53", &t_str, "openbsm argument name 53" },
  { "openbsm.arg54", &t_uint, "openbsm argument 54" },
  { "openbsm.argname54", &t_str, "openbsm argument name 54" },
  { "openbsm.arg55", &t_uint, "openbsm argument 55" },
  { "openbsm.argname55", &t_str, "openbsm argument name 55" },
  { "openbsm.arg56", &t_uint, "openbsm argument 56" },
  { "openbsm.argname56", &t_str, "openbsm argument name 56" },
  { "openbsm.arg57", &t_uint, "openbsm argument 57" },
  { "openbsm.argname57", &t_str, "openbsm argument name 57" },
  { "openbsm.arg58", &t_uint, "openbsm argument 58" },
  { "openbsm.argname58", &t_str, "openbsm argument name 58" },
  { "openbsm.arg59", &t_uint, "openbsm argument 59" },
  { "openbsm.argname59", &t_str, "openbsm argument name 59" },
  { "openbsm.arg60", &t_uint, "openbsm argument 60" },
  { "openbsm.argname60", &t_str, "openbsm argument name 60" },
  { "openbsm.arg61", &t_uint, "openbsm argument 61" },
  { "openbsm.argname61", &t_str, "openbsm argument name 61" },
  { "openbsm.arg62", &t_uint, "openbsm argument 62" },
  { "openbsm.argname62", &t_str, "openbsm argument name 62" },
  { "openbsm.arg63", &t_uint, "openbsm argument 63" },
  { "openbsm.argname63", &t_str, "openbsm argument name 63" },
  { "openbsm.arg64", &t_uint, "openbsm argument 64" },
  { "openbsm.argname64", &t_str, "openbsm argument name 64" },
  { "openbsm.arg65", &t_uint, "openbsm argument 65" },
  { "openbsm.argname65", &t_str, "openbsm argument name 65" },
  { "openbsm.arg66", &t_uint, "openbsm argument 66" },
  { "openbsm.argname66", &t_str, "openbsm argument name 66" },
  { "openbsm.arg67", &t_uint, "openbsm argument 67" },
  { "openbsm.argname67", &t_str, "openbsm argument name 67" },
  { "openbsm.arg68", &t_uint, "openbsm argument 68" },
  { "openbsm.argname68", &t_str, "openbsm argument name 68" },
  { "openbsm.arg69", &t_uint, "openbsm argument 69" },
  { "openbsm.argname69", &t_str, "openbsm argument name 69" },
  { "openbsm.arg70", &t_uint, "openbsm argument 70" },
  { "openbsm.argname70", &t_str, "openbsm argument name 70" },
  { "openbsm.arg71", &t_uint, "openbsm argument 71" },
  { "openbsm.argname71", &t_str, "openbsm argument name 71" },
  { "openbsm.arg72", &t_uint, "openbsm argument 72" },
  { "openbsm.argname72", &t_str, "openbsm argument name 72" },
  { "openbsm.arg73", &t_uint, "openbsm argument 73" },
  { "openbsm.argname73", &t_str, "openbsm argument name 73" },
  { "openbsm.arg74", &t_uint, "openbsm argument 74" },
  { "openbsm.argname74", &t_str, "openbsm argument name 74" },
  { "openbsm.arg75", &t_uint, "openbsm argument 75" },
  { "openbsm.argname75", &t_str, "openbsm argument name 75" },
  { "openbsm.arg76", &t_uint, "openbsm argument 76" },
  { "openbsm.argname76", &t_str, "openbsm argument name 76" },
  { "openbsm.arg77", &t_uint, "openbsm argument 77" },
  { "openbsm.argname77", &t_str, "openbsm argument name 77" },
  { "openbsm.arg78", &t_uint, "openbsm argument 78" },
  { "openbsm.argname78", &t_str, "openbsm argument name 78" },
  { "openbsm.arg79", &t_uint, "openbsm argument 79" },
  { "openbsm.argname79", &t_str, "openbsm argument name 79" },
  { "openbsm.arg80", &t_uint, "openbsm argument 80" },
  { "openbsm.argname80", &t_str, "openbsm argument name 80" },
  { "openbsm.arg81", &t_uint, "openbsm argument 81" },
  { "openbsm.argname81", &t_str, "openbsm argument name 81" },
  { "openbsm.arg82", &t_uint, "openbsm argument 82" },
  { "openbsm.argname82", &t_str, "openbsm argument name 82" },
  { "openbsm.arg83", &t_uint, "openbsm argument 83" },
  { "openbsm.argname83", &t_str, "openbsm argument name 83" },
  { "openbsm.arg84", &t_uint, "openbsm argument 84" },
  { "openbsm.argname84", &t_str, "openbsm argument name 84" },
  { "openbsm.arg85", &t_uint, "openbsm argument 85" },
  { "openbsm.argname85", &t_str, "openbsm argument name 85" },
  { "openbsm.arg86", &t_uint, "openbsm argument 86" },
  { "openbsm.argname86", &t_str, "openbsm argument name 86" },
  { "openbsm.arg87", &t_uint, "openbsm argument 87" },
  { "openbsm.argname87", &t_str, "openbsm argument name 87" },
  { "openbsm.arg88", &t_uint, "openbsm argument 88" },
  { "openbsm.argname88", &t_str, "openbsm argument name 88" },
  { "openbsm.arg89", &t_uint, "openbsm argument 89" },
  { "openbsm.argname89", &t_str, "openbsm argument name 89" },
  { "openbsm.arg90", &t_uint, "openbsm argument 90" },
  { "openbsm.argname90", &t_str, "openbsm argument name 90" },
  { "openbsm.arg91", &t_uint, "openbsm argument 91" },
  { "openbsm.argname91", &t_str, "openbsm argument name 91" },
  { "openbsm.arg92", &t_uint, "openbsm argument 92" },
  { "openbsm.argname92", &t_str, "openbsm argument name 92" },
  { "openbsm.arg93", &t_uint, "openbsm argument 93" },
  { "openbsm.argname93", &t_str, "openbsm argument name 93" },
  { "openbsm.arg94", &t_uint, "openbsm argument 94" },
  { "openbsm.argname94", &t_str, "openbsm argument name 94" },
  { "openbsm.arg95", &t_uint, "openbsm argument 95" },
  { "openbsm.argname95", &t_str, "openbsm argument name 95" },
  { "openbsm.arg96", &t_uint, "openbsm argument 96" },
  { "openbsm.argname96", &t_str, "openbsm argument name 96" },
  { "openbsm.arg97", &t_uint, "openbsm argument 97" },
  { "openbsm.argname97", &t_str, "openbsm argument name 97" },
  { "openbsm.arg98", &t_uint, "openbsm argument 98" },
  { "openbsm.argname98", &t_str, "openbsm argument name 98" },
  { "openbsm.arg99", &t_uint, "openbsm argument 99" },
  { "openbsm.argname99", &t_str, "openbsm argument name 99" },
  { "openbsm.arg100", &t_uint, "openbsm argument 100" },
  { "openbsm.argname100", &t_str, "openbsm argument name 100" },
  { "openbsm.arg101", &t_uint, "openbsm argument 101" },
  { "openbsm.argname101", &t_str, "openbsm argument name 101" },
  { "openbsm.arg102", &t_uint, "openbsm argument 102" },
  { "openbsm.argname102", &t_str, "openbsm argument name 102" },
  { "openbsm.arg103", &t_uint, "openbsm argument 103" },
  { "openbsm.argname103", &t_str, "openbsm argument name 103" },
  { "openbsm.arg104", &t_uint, "openbsm argument 104" },
  { "openbsm.argname104", &t_str, "openbsm argument name 104" },
  { "openbsm.arg105", &t_uint, "openbsm argument 105" },
  { "openbsm.argname105", &t_str, "openbsm argument name 105" },
  { "openbsm.arg106", &t_uint, "openbsm argument 106" },
  { "openbsm.argname106", &t_str, "openbsm argument name 106" },
  { "openbsm.arg107", &t_uint, "openbsm argument 107" },
  { "openbsm.argname107", &t_str, "openbsm argument name 107" },
  { "openbsm.arg108", &t_uint, "openbsm argument 108" },
  { "openbsm.argname108", &t_str, "openbsm argument name 108" },
  { "openbsm.arg109", &t_uint, "openbsm argument 109" },
  { "openbsm.argname109", &t_str, "openbsm argument name 109" },
  { "openbsm.arg110", &t_uint, "openbsm argument 110" },
  { "openbsm.argname110", &t_str, "openbsm argument name 110" },
  { "openbsm.arg111", &t_uint, "openbsm argument 111" },
  { "openbsm.argname111", &t_str, "openbsm argument name 111" },
  { "openbsm.arg112", &t_uint, "openbsm argument 112" },
  { "openbsm.argname112", &t_str, "openbsm argument name 112" },
  { "openbsm.arg113", &t_uint, "openbsm argument 113" },
  { "openbsm.argname113", &t_str, "openbsm argument name 113" },
  { "openbsm.arg114", &t_uint, "openbsm argument 114" },
  { "openbsm.argname114", &t_str, "openbsm argument name 114" },
  { "openbsm.arg115", &t_uint, "openbsm argument 115" },
  { "openbsm.argname115", &t_str, "openbsm argument name 115" },
  { "openbsm.arg116", &t_uint, "openbsm argument 116" },
  { "openbsm.argname116", &t_str, "openbsm argument name 116" },
  { "openbsm.arg117", &t_uint, "openbsm argument 117" },
  { "openbsm.argname117", &t_str, "openbsm argument name 117" },
  { "openbsm.arg118", &t_uint, "openbsm argument 118" },
  { "openbsm.argname118", &t_str, "openbsm argument name 118" },
  { "openbsm.arg119", &t_uint, "openbsm argument 119" },
  { "openbsm.argname119", &t_str, "openbsm argument name 119" },
  { "openbsm.arg120", &t_uint, "openbsm argument 120" },
  { "openbsm.argname120", &t_str, "openbsm argument name 120" },
  { "openbsm.arg121", &t_uint, "openbsm argument 121" },
  { "openbsm.argname121", &t_str, "openbsm argument name 121" },
  { "openbsm.arg122", &t_uint, "openbsm argument 122" },
  { "openbsm.argname122", &t_str, "openbsm argument name 122" },
  { "openbsm.arg123", &t_uint, "openbsm argument 123" },
  { "openbsm.argname123", &t_str, "openbsm argument name 123" },
  { "openbsm.arg124", &t_uint, "openbsm argument 124" },
  { "openbsm.argname124", &t_str, "openbsm argument name 124" },
  { "openbsm.arg125", &t_uint, "openbsm argument 125" },
  { "openbsm.argname125", &t_str, "openbsm argument name 125" },
  { "openbsm.arg126", &t_uint, "openbsm argument 126" },
  { "openbsm.argname126", &t_str, "openbsm argument name 126" },
  { "openbsm.arg127", &t_uint, "openbsm argument 127" },
  { "openbsm.argname127", &t_str, "openbsm argument name 127" },
  { "openbsm.arg128", &t_uint, "openbsm argument 128" },
  { "openbsm.argname128", &t_str, "openbsm argument name 128" },
#define F_OPENBSM_ARG_END (F_OPENBSM_ARG_START+256)
#define F_OPENBSM_EXECARG_START F_OPENBSM_ARG_END
  { "bsm.execarg_num", &t_uint, "bsm exec argument number" },
#define F_OPENBSM_EXECARG_NUM 0
  { "bsm.execarg1", &t_str, "openbsm exec argument 1" },
  { "bsm.execarg2", &t_str, "openbsm exec argument 2" },
  { "bsm.execarg3", &t_str, "openbsm exec argument 3" },
  { "bsm.execarg4", &t_str, "openbsm exec argument 4" },
  { "bsm.execarg5", &t_str, "openbsm exec argument 5" },
  { "bsm.execarg6", &t_str, "openbsm exec argument 6" },
  { "bsm.execarg7", &t_str, "openbsm exec argument 7" },
  { "bsm.execarg8", &t_str, "openbsm exec argument 8" },
  { "bsm.execarg9", &t_str, "openbsm exec argument 9" },
  { "bsm.execarg10", &t_str, "openbsm exec argument 10" },
  { "bsm.execarg11", &t_str, "openbsm exec argument 11" },
  { "bsm.execarg12", &t_str, "openbsm exec argument 12" },
  { "bsm.execarg13", &t_str, "openbsm exec argument 13" },
  { "bsm.execarg14", &t_str, "openbsm exec argument 14" },
  { "bsm.execarg15", &t_str, "openbsm exec argument 15" },
  { "bsm.execarg16", &t_str, "openbsm exec argument 16" },
  { "bsm.execarg17", &t_str, "openbsm exec argument 17" },
  { "bsm.execarg18", &t_str, "openbsm exec argument 18" },
  { "bsm.execarg19", &t_str, "openbsm exec argument 19" },
  { "bsm.execarg20", &t_str, "openbsm exec argument 20" },
  { "bsm.execarg21", &t_str, "openbsm exec argument 21" },
  { "bsm.execarg22", &t_str, "openbsm exec argument 22" },
  { "bsm.execarg23", &t_str, "openbsm exec argument 23" },
  { "bsm.execarg24", &t_str, "openbsm exec argument 24" },
  { "bsm.execarg25", &t_str, "openbsm exec argument 25" },
  { "bsm.execarg26", &t_str, "openbsm exec argument 26" },
  { "bsm.execarg27", &t_str, "openbsm exec argument 27" },
  { "bsm.execarg28", &t_str, "openbsm exec argument 28" },
  { "bsm.execarg29", &t_str, "openbsm exec argument 29" },
  { "bsm.execarg30", &t_str, "openbsm exec argument 30" },
  { "bsm.execarg31", &t_str, "openbsm exec argument 31" },
  { "bsm.execarg32", &t_str, "openbsm exec argument 32" },
  { "bsm.execarg33", &t_str, "openbsm exec argument 33" },
  { "bsm.execarg34", &t_str, "openbsm exec argument 34" },
  { "bsm.execarg35", &t_str, "openbsm exec argument 35" },
  { "bsm.execarg36", &t_str, "openbsm exec argument 36" },
  { "bsm.execarg37", &t_str, "openbsm exec argument 37" },
  { "bsm.execarg38", &t_str, "openbsm exec argument 38" },
  { "bsm.execarg39", &t_str, "openbsm exec argument 39" },
  { "bsm.execarg40", &t_str, "openbsm exec argument 40" },
  { "bsm.execarg41", &t_str, "openbsm exec argument 41" },
  { "bsm.execarg42", &t_str, "openbsm exec argument 42" },
  { "bsm.execarg43", &t_str, "openbsm exec argument 43" },
  { "bsm.execarg44", &t_str, "openbsm exec argument 44" },
  { "bsm.execarg45", &t_str, "openbsm exec argument 45" },
  { "bsm.execarg46", &t_str, "openbsm exec argument 46" },
  { "bsm.execarg47", &t_str, "openbsm exec argument 47" },
  { "bsm.execarg48", &t_str, "openbsm exec argument 48" },
  { "bsm.execarg49", &t_str, "openbsm exec argument 49" },
  { "bsm.execarg50", &t_str, "openbsm exec argument 50" },
  { "bsm.execarg51", &t_str, "openbsm exec argument 51" },
  { "bsm.execarg52", &t_str, "openbsm exec argument 52" },
  { "bsm.execarg53", &t_str, "openbsm exec argument 53" },
  { "bsm.execarg54", &t_str, "openbsm exec argument 54" },
  { "bsm.execarg55", &t_str, "openbsm exec argument 55" },
  { "bsm.execarg56", &t_str, "openbsm exec argument 56" },
  { "bsm.execarg57", &t_str, "openbsm exec argument 57" },
  { "bsm.execarg58", &t_str, "openbsm exec argument 58" },
  { "bsm.execarg59", &t_str, "openbsm exec argument 59" },
  { "bsm.execarg60", &t_str, "openbsm exec argument 60" },
  { "bsm.execarg61", &t_str, "openbsm exec argument 61" },
  { "bsm.execarg62", &t_str, "openbsm exec argument 62" },
  { "bsm.execarg63", &t_str, "openbsm exec argument 63" },
  { "bsm.execarg64", &t_str, "openbsm exec argument 64" },
  { "bsm.execarg65", &t_str, "openbsm exec argument 65" },
  { "bsm.execarg66", &t_str, "openbsm exec argument 66" },
  { "bsm.execarg67", &t_str, "openbsm exec argument 67" },
  { "bsm.execarg68", &t_str, "openbsm exec argument 68" },
  { "bsm.execarg69", &t_str, "openbsm exec argument 69" },
  { "bsm.execarg70", &t_str, "openbsm exec argument 70" },
  { "bsm.execarg71", &t_str, "openbsm exec argument 71" },
  { "bsm.execarg72", &t_str, "openbsm exec argument 72" },
  { "bsm.execarg73", &t_str, "openbsm exec argument 73" },
  { "bsm.execarg74", &t_str, "openbsm exec argument 74" },
  { "bsm.execarg75", &t_str, "openbsm exec argument 75" },
  { "bsm.execarg76", &t_str, "openbsm exec argument 76" },
  { "bsm.execarg77", &t_str, "openbsm exec argument 77" },
  { "bsm.execarg78", &t_str, "openbsm exec argument 78" },
  { "bsm.execarg79", &t_str, "openbsm exec argument 79" },
  { "bsm.execarg80", &t_str, "openbsm exec argument 80" },
  { "bsm.execarg81", &t_str, "openbsm exec argument 81" },
  { "bsm.execarg82", &t_str, "openbsm exec argument 82" },
  { "bsm.execarg83", &t_str, "openbsm exec argument 83" },
  { "bsm.execarg84", &t_str, "openbsm exec argument 84" },
  { "bsm.execarg85", &t_str, "openbsm exec argument 85" },
  { "bsm.execarg86", &t_str, "openbsm exec argument 86" },
  { "bsm.execarg87", &t_str, "openbsm exec argument 87" },
  { "bsm.execarg88", &t_str, "openbsm exec argument 88" },
  { "bsm.execarg89", &t_str, "openbsm exec argument 89" },
  { "bsm.execarg90", &t_str, "openbsm exec argument 90" },
  { "bsm.execarg91", &t_str, "openbsm exec argument 91" },
  { "bsm.execarg92", &t_str, "openbsm exec argument 92" },
  { "bsm.execarg93", &t_str, "openbsm exec argument 93" },
  { "bsm.execarg94", &t_str, "openbsm exec argument 94" },
  { "bsm.execarg95", &t_str, "openbsm exec argument 95" },
  { "bsm.execarg96", &t_str, "openbsm exec argument 96" },
  { "bsm.execarg97", &t_str, "openbsm exec argument 97" },
  { "bsm.execarg98", &t_str, "openbsm exec argument 98" },
  { "bsm.execarg99", &t_str, "openbsm exec argument 99" },
  { "bsm.execarg100", &t_str, "openbsm exec argument 100" },
  { "bsm.execarg101", &t_str, "openbsm exec argument 101" },
  { "bsm.execarg102", &t_str, "openbsm exec argument 102" },
  { "bsm.execarg103", &t_str, "openbsm exec argument 103" },
  { "bsm.execarg104", &t_str, "openbsm exec argument 104" },
  { "bsm.execarg105", &t_str, "openbsm exec argument 105" },
  { "bsm.execarg106", &t_str, "openbsm exec argument 106" },
  { "bsm.execarg107", &t_str, "openbsm exec argument 107" },
  { "bsm.execarg108", &t_str, "openbsm exec argument 108" },
  { "bsm.execarg109", &t_str, "openbsm exec argument 109" },
  { "bsm.execarg110", &t_str, "openbsm exec argument 110" },
  { "bsm.execarg111", &t_str, "openbsm exec argument 111" },
  { "bsm.execarg112", &t_str, "openbsm exec argument 112" },
  { "bsm.execarg113", &t_str, "openbsm exec argument 113" },
  { "bsm.execarg114", &t_str, "openbsm exec argument 114" },
  { "bsm.execarg115", &t_str, "openbsm exec argument 115" },
  { "bsm.execarg116", &t_str, "openbsm exec argument 116" },
  { "bsm.execarg117", &t_str, "openbsm exec argument 117" },
  { "bsm.execarg118", &t_str, "openbsm exec argument 118" },
  { "bsm.execarg119", &t_str, "openbsm exec argument 119" },
  { "bsm.execarg120", &t_str, "openbsm exec argument 120" },
  { "bsm.execarg121", &t_str, "openbsm exec argument 121" },
  { "bsm.execarg122", &t_str, "openbsm exec argument 122" },
  { "bsm.execarg123", &t_str, "openbsm exec argument 123" },
  { "bsm.execarg124", &t_str, "openbsm exec argument 124" },
  { "bsm.execarg125", &t_str, "openbsm exec argument 125" },
  { "bsm.execarg126", &t_str, "openbsm exec argument 126" },
  { "bsm.execarg127", &t_str, "openbsm exec argument 127" },
  { "bsm.execarg128", &t_str, "openbsm exec argument 128" },
#define F_OPENBSM_EXECARG_END (F_OPENBSM_EXECARG_START+129)
#define F_OPENBSM_EXECENV_START F_OPENBSM_EXECARG_END
  { "bsm.execenv_num", &t_uint, "bsm exec number of environment variables" },
#define F_OPENBSM_EXECENV_NUM 0
  { "bsm.execenv1", &t_str, "openbsm exec environment variable 1" },
  { "bsm.execenv2", &t_str, "openbsm exec environment variable 2" },
  { "bsm.execenv3", &t_str, "openbsm exec environment variable 3" },
  { "bsm.execenv4", &t_str, "openbsm exec environment variable 4" },
  { "bsm.execenv5", &t_str, "openbsm exec environment variable 5" },
  { "bsm.execenv6", &t_str, "openbsm exec environment variable 6" },
  { "bsm.execenv7", &t_str, "openbsm exec environment variable 7" },
  { "bsm.execenv8", &t_str, "openbsm exec environment variable 8" },
  { "bsm.execenv9", &t_str, "openbsm exec environment variable 9" },
  { "bsm.execenv10", &t_str, "openbsm exec environment variable 10" },
  { "bsm.execenv11", &t_str, "openbsm exec environment variable 11" },
  { "bsm.execenv12", &t_str, "openbsm exec environment variable 12" },
  { "bsm.execenv13", &t_str, "openbsm exec environment variable 13" },
  { "bsm.execenv14", &t_str, "openbsm exec environment variable 14" },
  { "bsm.execenv15", &t_str, "openbsm exec environment variable 15" },
  { "bsm.execenv16", &t_str, "openbsm exec environment variable 16" },
  { "bsm.execenv17", &t_str, "openbsm exec environment variable 17" },
  { "bsm.execenv18", &t_str, "openbsm exec environment variable 18" },
  { "bsm.execenv19", &t_str, "openbsm exec environment variable 19" },
  { "bsm.execenv20", &t_str, "openbsm exec environment variable 20" },
  { "bsm.execenv21", &t_str, "openbsm exec environment variable 21" },
  { "bsm.execenv22", &t_str, "openbsm exec environment variable 22" },
  { "bsm.execenv23", &t_str, "openbsm exec environment variable 23" },
  { "bsm.execenv24", &t_str, "openbsm exec environment variable 24" },
  { "bsm.execenv25", &t_str, "openbsm exec environment variable 25" },
  { "bsm.execenv26", &t_str, "openbsm exec environment variable 26" },
  { "bsm.execenv27", &t_str, "openbsm exec environment variable 27" },
  { "bsm.execenv28", &t_str, "openbsm exec environment variable 28" },
  { "bsm.execenv29", &t_str, "openbsm exec environment variable 29" },
  { "bsm.execenv30", &t_str, "openbsm exec environment variable 30" },
  { "bsm.execenv31", &t_str, "openbsm exec environment variable 31" },
  { "bsm.execenv32", &t_str, "openbsm exec environment variable 32" },
  { "bsm.execenv33", &t_str, "openbsm exec environment variable 33" },
  { "bsm.execenv34", &t_str, "openbsm exec environment variable 34" },
  { "bsm.execenv35", &t_str, "openbsm exec environment variable 35" },
  { "bsm.execenv36", &t_str, "openbsm exec environment variable 36" },
  { "bsm.execenv37", &t_str, "openbsm exec environment variable 37" },
  { "bsm.execenv38", &t_str, "openbsm exec environment variable 38" },
  { "bsm.execenv39", &t_str, "openbsm exec environment variable 39" },
  { "bsm.execenv40", &t_str, "openbsm exec environment variable 40" },
  { "bsm.execenv41", &t_str, "openbsm exec environment variable 41" },
  { "bsm.execenv42", &t_str, "openbsm exec environment variable 42" },
  { "bsm.execenv43", &t_str, "openbsm exec environment variable 43" },
  { "bsm.execenv44", &t_str, "openbsm exec environment variable 44" },
  { "bsm.execenv45", &t_str, "openbsm exec environment variable 45" },
  { "bsm.execenv46", &t_str, "openbsm exec environment variable 46" },
  { "bsm.execenv47", &t_str, "openbsm exec environment variable 47" },
  { "bsm.execenv48", &t_str, "openbsm exec environment variable 48" },
  { "bsm.execenv49", &t_str, "openbsm exec environment variable 49" },
  { "bsm.execenv50", &t_str, "openbsm exec environment variable 50" },
  { "bsm.execenv51", &t_str, "openbsm exec environment variable 51" },
  { "bsm.execenv52", &t_str, "openbsm exec environment variable 52" },
  { "bsm.execenv53", &t_str, "openbsm exec environment variable 53" },
  { "bsm.execenv54", &t_str, "openbsm exec environment variable 54" },
  { "bsm.execenv55", &t_str, "openbsm exec environment variable 55" },
  { "bsm.execenv56", &t_str, "openbsm exec environment variable 56" },
  { "bsm.execenv57", &t_str, "openbsm exec environment variable 57" },
  { "bsm.execenv58", &t_str, "openbsm exec environment variable 58" },
  { "bsm.execenv59", &t_str, "openbsm exec environment variable 59" },
  { "bsm.execenv60", &t_str, "openbsm exec environment variable 60" },
  { "bsm.execenv61", &t_str, "openbsm exec environment variable 61" },
  { "bsm.execenv62", &t_str, "openbsm exec environment variable 62" },
  { "bsm.execenv63", &t_str, "openbsm exec environment variable 63" },
  { "bsm.execenv64", &t_str, "openbsm exec environment variable 64" },
  { "bsm.execenv65", &t_str, "openbsm exec environment variable 65" },
  { "bsm.execenv66", &t_str, "openbsm exec environment variable 66" },
  { "bsm.execenv67", &t_str, "openbsm exec environment variable 67" },
  { "bsm.execenv68", &t_str, "openbsm exec environment variable 68" },
  { "bsm.execenv69", &t_str, "openbsm exec environment variable 69" },
  { "bsm.execenv70", &t_str, "openbsm exec environment variable 70" },
  { "bsm.execenv71", &t_str, "openbsm exec environment variable 71" },
  { "bsm.execenv72", &t_str, "openbsm exec environment variable 72" },
  { "bsm.execenv73", &t_str, "openbsm exec environment variable 73" },
  { "bsm.execenv74", &t_str, "openbsm exec environment variable 74" },
  { "bsm.execenv75", &t_str, "openbsm exec environment variable 75" },
  { "bsm.execenv76", &t_str, "openbsm exec environment variable 76" },
  { "bsm.execenv77", &t_str, "openbsm exec environment variable 77" },
  { "bsm.execenv78", &t_str, "openbsm exec environment variable 78" },
  { "bsm.execenv79", &t_str, "openbsm exec environment variable 79" },
  { "bsm.execenv80", &t_str, "openbsm exec environment variable 80" },
  { "bsm.execenv81", &t_str, "openbsm exec environment variable 81" },
  { "bsm.execenv82", &t_str, "openbsm exec environment variable 82" },
  { "bsm.execenv83", &t_str, "openbsm exec environment variable 83" },
  { "bsm.execenv84", &t_str, "openbsm exec environment variable 84" },
  { "bsm.execenv85", &t_str, "openbsm exec environment variable 85" },
  { "bsm.execenv86", &t_str, "openbsm exec environment variable 86" },
  { "bsm.execenv87", &t_str, "openbsm exec environment variable 87" },
  { "bsm.execenv88", &t_str, "openbsm exec environment variable 88" },
  { "bsm.execenv89", &t_str, "openbsm exec environment variable 89" },
  { "bsm.execenv90", &t_str, "openbsm exec environment variable 90" },
  { "bsm.execenv91", &t_str, "openbsm exec environment variable 91" },
  { "bsm.execenv92", &t_str, "openbsm exec environment variable 92" },
  { "bsm.execenv93", &t_str, "openbsm exec environment variable 93" },
  { "bsm.execenv94", &t_str, "openbsm exec environment variable 94" },
  { "bsm.execenv95", &t_str, "openbsm exec environment variable 95" },
  { "bsm.execenv96", &t_str, "openbsm exec environment variable 96" },
  { "bsm.execenv97", &t_str, "openbsm exec environment variable 97" },
  { "bsm.execenv98", &t_str, "openbsm exec environment variable 98" },
  { "bsm.execenv99", &t_str, "openbsm exec environment variable 99" },
  { "bsm.execenv100", &t_str, "openbsm exec environment variable 100" },
  { "bsm.execenv101", &t_str, "openbsm exec environment variable 101" },
  { "bsm.execenv102", &t_str, "openbsm exec environment variable 102" },
  { "bsm.execenv103", &t_str, "openbsm exec environment variable 103" },
  { "bsm.execenv104", &t_str, "openbsm exec environment variable 104" },
  { "bsm.execenv105", &t_str, "openbsm exec environment variable 105" },
  { "bsm.execenv106", &t_str, "openbsm exec environment variable 106" },
  { "bsm.execenv107", &t_str, "openbsm exec environment variable 107" },
  { "bsm.execenv108", &t_str, "openbsm exec environment variable 108" },
  { "bsm.execenv109", &t_str, "openbsm exec environment variable 109" },
  { "bsm.execenv110", &t_str, "openbsm exec environment variable 110" },
  { "bsm.execenv111", &t_str, "openbsm exec environment variable 111" },
  { "bsm.execenv112", &t_str, "openbsm exec environment variable 112" },
  { "bsm.execenv113", &t_str, "openbsm exec environment variable 113" },
  { "bsm.execenv114", &t_str, "openbsm exec environment variable 114" },
  { "bsm.execenv115", &t_str, "openbsm exec environment variable 115" },
  { "bsm.execenv116", &t_str, "openbsm exec environment variable 116" },
  { "bsm.execenv117", &t_str, "openbsm exec environment variable 117" },
  { "bsm.execenv118", &t_str, "openbsm exec environment variable 118" },
  { "bsm.execenv119", &t_str, "openbsm exec environment variable 119" },
  { "bsm.execenv120", &t_str, "openbsm exec environment variable 120" },
  { "bsm.execenv121", &t_str, "openbsm exec environment variable 121" },
  { "bsm.execenv122", &t_str, "openbsm exec environment variable 122" },
  { "bsm.execenv123", &t_str, "openbsm exec environment variable 123" },
  { "bsm.execenv124", &t_str, "openbsm exec environment variable 124" },
  { "bsm.execenv125", &t_str, "openbsm exec environment variable 125" },
  { "bsm.execenv126", &t_str, "openbsm exec environment variable 126" },
  { "bsm.execenv127", &t_str, "openbsm exec environment variable 127" },
  { "bsm.execenv128", &t_str, "openbsm exec environment variable 128" },
#define F_OPENBSM_EXECENV_END (F_OPENBSM_EXECENV_START+129)
#define F_OPENBSM_NEWGROUPS_START F_OPENBSM_EXECENV_END
  { "bsm.newgroups_num", &t_uint, "bsm number of new groups" },
#define F_OPENBSM_NEWGROUPS_NUM 0
  { "bsm.newgroup1", &t_uint, "openbsm new group 1" },
  { "bsm.newgroup2", &t_uint, "openbsm new group 2" },
  { "bsm.newgroup3", &t_uint, "openbsm new group 3" },
  { "bsm.newgroup4", &t_uint, "openbsm new group 4" },
  { "bsm.newgroup5", &t_uint, "openbsm new group 5" },
  { "bsm.newgroup6", &t_uint, "openbsm new group 6" },
  { "bsm.newgroup7", &t_uint, "openbsm new group 7" },
  { "bsm.newgroup8", &t_uint, "openbsm new group 8" },
  { "bsm.newgroup9", &t_uint, "openbsm new group 9" },
  { "bsm.newgroup10", &t_uint, "openbsm new group 10" },
  { "bsm.newgroup11", &t_uint, "openbsm new group 11" },
  { "bsm.newgroup12", &t_uint, "openbsm new group 12" },
  { "bsm.newgroup13", &t_uint, "openbsm new group 13" },
  { "bsm.newgroup14", &t_uint, "openbsm new group 14" },
  { "bsm.newgroup15", &t_uint, "openbsm new group 15" },
  { "bsm.newgroup16", &t_uint, "openbsm new group 16" },
#define F_OPENBSM_NEWGROUPS_END (F_OPENBSM_NEWGROUPS_START+17)
#define OPENBSM_FIELDS F_OPENBSM_NEWGROUPS_END
