// Generated automatically by gen_mod_bsm.c: do not touch!
// Copyright, license: see file gen_mod.bsm.c.
  { "bsm.groups.len", T_INT, "bsm groups: number of groups" },
  { "bsm.groups.elt1", T_INT, "bsm groups: element no. 1" },
  { "bsm.groups.elt2", T_INT, "bsm groups: element no. 2" },
  { "bsm.groups.elt3", T_INT, "bsm groups: element no. 3" },
  { "bsm.groups.elt4", T_INT, "bsm groups: element no. 4" },
  { "bsm.groups.elt5", T_INT, "bsm groups: element no. 5" },
  { "bsm.groups.elt6", T_INT, "bsm groups: element no. 6" },
  { "bsm.groups.elt7", T_INT, "bsm groups: element no. 7" },
  { "bsm.groups.elt8", T_INT, "bsm groups: element no. 8" },
  { "bsm.groups.elt9", T_INT, "bsm groups: element no. 9" },
  { "bsm.groups.elt10", T_INT, "bsm groups: element no. 10" },
  { "bsm.groups.elt11", T_INT, "bsm groups: element no. 11" },
  { "bsm.groups.elt12", T_INT, "bsm groups: element no. 12" },
  { "bsm.groups.elt13", T_INT, "bsm groups: element no. 13" },
  { "bsm.groups.elt14", T_INT, "bsm groups: element no. 14" },
  { "bsm.groups.elt15", T_INT, "bsm groups: element no. 15" },
  { "bsm.groups.elt16", T_INT, "bsm groups: element no. 16" },
  { "bsm.newgroups.len", T_INT, "bsm newgroups: number of groups" },
  { "bsm.newgroups.elt1", T_INT, "bsm newgroups: element no. 1" },
  { "bsm.newgroups.elt2", T_INT, "bsm newgroups: element no. 2" },
  { "bsm.newgroups.elt3", T_INT, "bsm newgroups: element no. 3" },
  { "bsm.newgroups.elt4", T_INT, "bsm newgroups: element no. 4" },
  { "bsm.newgroups.elt5", T_INT, "bsm newgroups: element no. 5" },
  { "bsm.newgroups.elt6", T_INT, "bsm newgroups: element no. 6" },
  { "bsm.newgroups.elt7", T_INT, "bsm newgroups: element no. 7" },
  { "bsm.newgroups.elt8", T_INT, "bsm newgroups: element no. 8" },
  { "bsm.newgroups.elt9", T_INT, "bsm newgroups: element no. 9" },
  { "bsm.newgroups.elt10", T_INT, "bsm newgroups: element no. 10" },
  { "bsm.newgroups.elt11", T_INT, "bsm newgroups: element no. 11" },
  { "bsm.newgroups.elt12", T_INT, "bsm newgroups: element no. 12" },
  { "bsm.newgroups.elt13", T_INT, "bsm newgroups: element no. 13" },
  { "bsm.newgroups.elt14", T_INT, "bsm newgroups: element no. 14" },
  { "bsm.newgroups.elt15", T_INT, "bsm newgroups: element no. 15" },
  { "bsm.newgroups.elt16", T_INT, "bsm newgroups: element no. 16" },
  { "bsm.execargs.len", T_INT, "bsm execargs: number of arguments" },
  { "bsm.execargs.elt1", T_STR, "bsm execargs: element no. 1" },
  { "bsm.execargs.elt2", T_STR, "bsm execargs: element no. 2" },
  { "bsm.execargs.elt3", T_STR, "bsm execargs: element no. 3" },
  { "bsm.execargs.elt4", T_STR, "bsm execargs: element no. 4" },
  { "bsm.execargs.elt5", T_STR, "bsm execargs: element no. 5" },
  { "bsm.execargs.elt6", T_STR, "bsm execargs: element no. 6" },
  { "bsm.execargs.elt7", T_STR, "bsm execargs: element no. 7" },
  { "bsm.execargs.elt8", T_STR, "bsm execargs: element no. 8" },
  { "bsm.execargs.elt9", T_STR, "bsm execargs: element no. 9" },
  { "bsm.execargs.elt10", T_STR, "bsm execargs: element no. 10" },
  { "bsm.execargs.elt11", T_STR, "bsm execargs: element no. 11" },
  { "bsm.execargs.elt12", T_STR, "bsm execargs: element no. 12" },
  { "bsm.execargs.elt13", T_STR, "bsm execargs: element no. 13" },
  { "bsm.execargs.elt14", T_STR, "bsm execargs: element no. 14" },
  { "bsm.execargs.elt15", T_STR, "bsm execargs: element no. 15" },
  { "bsm.execargs.elt16", T_STR, "bsm execargs: element no. 16" },
  { "bsm.execargs.elt17", T_STR, "bsm execargs: element no. 17" },
  { "bsm.execargs.elt18", T_STR, "bsm execargs: element no. 18" },
  { "bsm.execargs.elt19", T_STR, "bsm execargs: element no. 19" },
  { "bsm.execargs.elt20", T_STR, "bsm execargs: element no. 20" },
  { "bsm.execargs.elt21", T_STR, "bsm execargs: element no. 21" },
  { "bsm.execargs.elt22", T_STR, "bsm execargs: element no. 22" },
  { "bsm.execargs.elt23", T_STR, "bsm execargs: element no. 23" },
  { "bsm.execargs.elt24", T_STR, "bsm execargs: element no. 24" },
  { "bsm.execargs.elt25", T_STR, "bsm execargs: element no. 25" },
  { "bsm.execargs.elt26", T_STR, "bsm execargs: element no. 26" },
  { "bsm.execargs.elt27", T_STR, "bsm execargs: element no. 27" },
  { "bsm.execargs.elt28", T_STR, "bsm execargs: element no. 28" },
  { "bsm.execargs.elt29", T_STR, "bsm execargs: element no. 29" },
  { "bsm.execargs.elt30", T_STR, "bsm execargs: element no. 30" },
  { "bsm.execargs.elt31", T_STR, "bsm execargs: element no. 31" },
  { "bsm.execargs.elt32", T_STR, "bsm execargs: element no. 32" },
  { "bsm.execargs.elt33", T_STR, "bsm execargs: element no. 33" },
  { "bsm.execargs.elt34", T_STR, "bsm execargs: element no. 34" },
  { "bsm.execargs.elt35", T_STR, "bsm execargs: element no. 35" },
  { "bsm.execargs.elt36", T_STR, "bsm execargs: element no. 36" },
  { "bsm.execargs.elt37", T_STR, "bsm execargs: element no. 37" },
  { "bsm.execargs.elt38", T_STR, "bsm execargs: element no. 38" },
  { "bsm.execargs.elt39", T_STR, "bsm execargs: element no. 39" },
  { "bsm.execargs.elt40", T_STR, "bsm execargs: element no. 40" },
  { "bsm.execargs.elt41", T_STR, "bsm execargs: element no. 41" },
  { "bsm.execargs.elt42", T_STR, "bsm execargs: element no. 42" },
  { "bsm.execargs.elt43", T_STR, "bsm execargs: element no. 43" },
  { "bsm.execargs.elt44", T_STR, "bsm execargs: element no. 44" },
  { "bsm.execargs.elt45", T_STR, "bsm execargs: element no. 45" },
  { "bsm.execargs.elt46", T_STR, "bsm execargs: element no. 46" },
  { "bsm.execargs.elt47", T_STR, "bsm execargs: element no. 47" },
  { "bsm.execargs.elt48", T_STR, "bsm execargs: element no. 48" },
  { "bsm.execargs.elt49", T_STR, "bsm execargs: element no. 49" },
  { "bsm.execargs.elt50", T_STR, "bsm execargs: element no. 50" },
  { "bsm.execargs.elt51", T_STR, "bsm execargs: element no. 51" },
  { "bsm.execargs.elt52", T_STR, "bsm execargs: element no. 52" },
  { "bsm.execargs.elt53", T_STR, "bsm execargs: element no. 53" },
  { "bsm.execargs.elt54", T_STR, "bsm execargs: element no. 54" },
  { "bsm.execargs.elt55", T_STR, "bsm execargs: element no. 55" },
  { "bsm.execargs.elt56", T_STR, "bsm execargs: element no. 56" },
  { "bsm.execargs.elt57", T_STR, "bsm execargs: element no. 57" },
  { "bsm.execargs.elt58", T_STR, "bsm execargs: element no. 58" },
  { "bsm.execargs.elt59", T_STR, "bsm execargs: element no. 59" },
  { "bsm.execargs.elt60", T_STR, "bsm execargs: element no. 60" },
  { "bsm.execargs.elt61", T_STR, "bsm execargs: element no. 61" },
  { "bsm.execargs.elt62", T_STR, "bsm execargs: element no. 62" },
  { "bsm.execargs.elt63", T_STR, "bsm execargs: element no. 63" },
  { "bsm.execargs.elt64", T_STR, "bsm execargs: element no. 64" },
  { "bsm.execargs.elt65", T_STR, "bsm execargs: element no. 65" },
  { "bsm.execargs.elt66", T_STR, "bsm execargs: element no. 66" },
  { "bsm.execargs.elt67", T_STR, "bsm execargs: element no. 67" },
  { "bsm.execargs.elt68", T_STR, "bsm execargs: element no. 68" },
  { "bsm.execargs.elt69", T_STR, "bsm execargs: element no. 69" },
  { "bsm.execargs.elt70", T_STR, "bsm execargs: element no. 70" },
  { "bsm.execargs.elt71", T_STR, "bsm execargs: element no. 71" },
  { "bsm.execargs.elt72", T_STR, "bsm execargs: element no. 72" },
  { "bsm.execargs.elt73", T_STR, "bsm execargs: element no. 73" },
  { "bsm.execargs.elt74", T_STR, "bsm execargs: element no. 74" },
  { "bsm.execargs.elt75", T_STR, "bsm execargs: element no. 75" },
  { "bsm.execargs.elt76", T_STR, "bsm execargs: element no. 76" },
  { "bsm.execargs.elt77", T_STR, "bsm execargs: element no. 77" },
  { "bsm.execargs.elt78", T_STR, "bsm execargs: element no. 78" },
  { "bsm.execargs.elt79", T_STR, "bsm execargs: element no. 79" },
  { "bsm.execargs.elt80", T_STR, "bsm execargs: element no. 80" },
  { "bsm.execargs.elt81", T_STR, "bsm execargs: element no. 81" },
  { "bsm.execargs.elt82", T_STR, "bsm execargs: element no. 82" },
  { "bsm.execargs.elt83", T_STR, "bsm execargs: element no. 83" },
  { "bsm.execargs.elt84", T_STR, "bsm execargs: element no. 84" },
  { "bsm.execargs.elt85", T_STR, "bsm execargs: element no. 85" },
  { "bsm.execargs.elt86", T_STR, "bsm execargs: element no. 86" },
  { "bsm.execargs.elt87", T_STR, "bsm execargs: element no. 87" },
  { "bsm.execargs.elt88", T_STR, "bsm execargs: element no. 88" },
  { "bsm.execargs.elt89", T_STR, "bsm execargs: element no. 89" },
  { "bsm.execargs.elt90", T_STR, "bsm execargs: element no. 90" },
  { "bsm.execargs.elt91", T_STR, "bsm execargs: element no. 91" },
  { "bsm.execargs.elt92", T_STR, "bsm execargs: element no. 92" },
  { "bsm.execargs.elt93", T_STR, "bsm execargs: element no. 93" },
  { "bsm.execargs.elt94", T_STR, "bsm execargs: element no. 94" },
  { "bsm.execargs.elt95", T_STR, "bsm execargs: element no. 95" },
  { "bsm.execargs.elt96", T_STR, "bsm execargs: element no. 96" },
  { "bsm.execargs.elt97", T_STR, "bsm execargs: element no. 97" },
  { "bsm.execargs.elt98", T_STR, "bsm execargs: element no. 98" },
  { "bsm.execargs.elt99", T_STR, "bsm execargs: element no. 99" },
  { "bsm.execargs.elt100", T_STR, "bsm execargs: element no. 100" },
  { "bsm.execargs.elt101", T_STR, "bsm execargs: element no. 101" },
  { "bsm.execargs.elt102", T_STR, "bsm execargs: element no. 102" },
  { "bsm.execargs.elt103", T_STR, "bsm execargs: element no. 103" },
  { "bsm.execargs.elt104", T_STR, "bsm execargs: element no. 104" },
  { "bsm.execargs.elt105", T_STR, "bsm execargs: element no. 105" },
  { "bsm.execargs.elt106", T_STR, "bsm execargs: element no. 106" },
  { "bsm.execargs.elt107", T_STR, "bsm execargs: element no. 107" },
  { "bsm.execargs.elt108", T_STR, "bsm execargs: element no. 108" },
  { "bsm.execargs.elt109", T_STR, "bsm execargs: element no. 109" },
  { "bsm.execargs.elt110", T_STR, "bsm execargs: element no. 110" },
  { "bsm.execargs.elt111", T_STR, "bsm execargs: element no. 111" },
  { "bsm.execargs.elt112", T_STR, "bsm execargs: element no. 112" },
  { "bsm.execargs.elt113", T_STR, "bsm execargs: element no. 113" },
  { "bsm.execargs.elt114", T_STR, "bsm execargs: element no. 114" },
  { "bsm.execargs.elt115", T_STR, "bsm execargs: element no. 115" },
  { "bsm.execargs.elt116", T_STR, "bsm execargs: element no. 116" },
  { "bsm.execargs.elt117", T_STR, "bsm execargs: element no. 117" },
  { "bsm.execargs.elt118", T_STR, "bsm execargs: element no. 118" },
  { "bsm.execargs.elt119", T_STR, "bsm execargs: element no. 119" },
  { "bsm.execargs.elt120", T_STR, "bsm execargs: element no. 120" },
  { "bsm.execargs.elt121", T_STR, "bsm execargs: element no. 121" },
  { "bsm.execargs.elt122", T_STR, "bsm execargs: element no. 122" },
  { "bsm.execargs.elt123", T_STR, "bsm execargs: element no. 123" },
  { "bsm.execargs.elt124", T_STR, "bsm execargs: element no. 124" },
  { "bsm.execargs.elt125", T_STR, "bsm execargs: element no. 125" },
  { "bsm.execargs.elt126", T_STR, "bsm execargs: element no. 126" },
  { "bsm.execargs.elt127", T_STR, "bsm execargs: element no. 127" },
  { "bsm.execargs.elt128", T_STR, "bsm execargs: element no. 128" },
  { "bsm.execenv.len", T_INT, "bsm execenv: number of environment variables" },
  { "bsm.execenv.elt1", T_STR, "bsm execenv: element no. 1" },
  { "bsm.execenv.elt2", T_STR, "bsm execenv: element no. 2" },
  { "bsm.execenv.elt3", T_STR, "bsm execenv: element no. 3" },
  { "bsm.execenv.elt4", T_STR, "bsm execenv: element no. 4" },
  { "bsm.execenv.elt5", T_STR, "bsm execenv: element no. 5" },
  { "bsm.execenv.elt6", T_STR, "bsm execenv: element no. 6" },
  { "bsm.execenv.elt7", T_STR, "bsm execenv: element no. 7" },
  { "bsm.execenv.elt8", T_STR, "bsm execenv: element no. 8" },
  { "bsm.execenv.elt9", T_STR, "bsm execenv: element no. 9" },
  { "bsm.execenv.elt10", T_STR, "bsm execenv: element no. 10" },
  { "bsm.execenv.elt11", T_STR, "bsm execenv: element no. 11" },
  { "bsm.execenv.elt12", T_STR, "bsm execenv: element no. 12" },
  { "bsm.execenv.elt13", T_STR, "bsm execenv: element no. 13" },
  { "bsm.execenv.elt14", T_STR, "bsm execenv: element no. 14" },
  { "bsm.execenv.elt15", T_STR, "bsm execenv: element no. 15" },
  { "bsm.execenv.elt16", T_STR, "bsm execenv: element no. 16" },
  { "bsm.execenv.elt17", T_STR, "bsm execenv: element no. 17" },
  { "bsm.execenv.elt18", T_STR, "bsm execenv: element no. 18" },
  { "bsm.execenv.elt19", T_STR, "bsm execenv: element no. 19" },
  { "bsm.execenv.elt20", T_STR, "bsm execenv: element no. 20" },
  { "bsm.execenv.elt21", T_STR, "bsm execenv: element no. 21" },
  { "bsm.execenv.elt22", T_STR, "bsm execenv: element no. 22" },
  { "bsm.execenv.elt23", T_STR, "bsm execenv: element no. 23" },
  { "bsm.execenv.elt24", T_STR, "bsm execenv: element no. 24" },
  { "bsm.execenv.elt25", T_STR, "bsm execenv: element no. 25" },
  { "bsm.execenv.elt26", T_STR, "bsm execenv: element no. 26" },
  { "bsm.execenv.elt27", T_STR, "bsm execenv: element no. 27" },
  { "bsm.execenv.elt28", T_STR, "bsm execenv: element no. 28" },
  { "bsm.execenv.elt29", T_STR, "bsm execenv: element no. 29" },
  { "bsm.execenv.elt30", T_STR, "bsm execenv: element no. 30" },
  { "bsm.execenv.elt31", T_STR, "bsm execenv: element no. 31" },
  { "bsm.execenv.elt32", T_STR, "bsm execenv: element no. 32" },
  { "bsm.execenv.elt33", T_STR, "bsm execenv: element no. 33" },
  { "bsm.execenv.elt34", T_STR, "bsm execenv: element no. 34" },
  { "bsm.execenv.elt35", T_STR, "bsm execenv: element no. 35" },
  { "bsm.execenv.elt36", T_STR, "bsm execenv: element no. 36" },
  { "bsm.execenv.elt37", T_STR, "bsm execenv: element no. 37" },
  { "bsm.execenv.elt38", T_STR, "bsm execenv: element no. 38" },
  { "bsm.execenv.elt39", T_STR, "bsm execenv: element no. 39" },
  { "bsm.execenv.elt40", T_STR, "bsm execenv: element no. 40" },
  { "bsm.execenv.elt41", T_STR, "bsm execenv: element no. 41" },
  { "bsm.execenv.elt42", T_STR, "bsm execenv: element no. 42" },
  { "bsm.execenv.elt43", T_STR, "bsm execenv: element no. 43" },
  { "bsm.execenv.elt44", T_STR, "bsm execenv: element no. 44" },
  { "bsm.execenv.elt45", T_STR, "bsm execenv: element no. 45" },
  { "bsm.execenv.elt46", T_STR, "bsm execenv: element no. 46" },
  { "bsm.execenv.elt47", T_STR, "bsm execenv: element no. 47" },
  { "bsm.execenv.elt48", T_STR, "bsm execenv: element no. 48" },
  { "bsm.execenv.elt49", T_STR, "bsm execenv: element no. 49" },
  { "bsm.execenv.elt50", T_STR, "bsm execenv: element no. 50" },
  { "bsm.execenv.elt51", T_STR, "bsm execenv: element no. 51" },
  { "bsm.execenv.elt52", T_STR, "bsm execenv: element no. 52" },
  { "bsm.execenv.elt53", T_STR, "bsm execenv: element no. 53" },
  { "bsm.execenv.elt54", T_STR, "bsm execenv: element no. 54" },
  { "bsm.execenv.elt55", T_STR, "bsm execenv: element no. 55" },
  { "bsm.execenv.elt56", T_STR, "bsm execenv: element no. 56" },
  { "bsm.execenv.elt57", T_STR, "bsm execenv: element no. 57" },
  { "bsm.execenv.elt58", T_STR, "bsm execenv: element no. 58" },
  { "bsm.execenv.elt59", T_STR, "bsm execenv: element no. 59" },
  { "bsm.execenv.elt60", T_STR, "bsm execenv: element no. 60" },
  { "bsm.execenv.elt61", T_STR, "bsm execenv: element no. 61" },
  { "bsm.execenv.elt62", T_STR, "bsm execenv: element no. 62" },
  { "bsm.execenv.elt63", T_STR, "bsm execenv: element no. 63" },
  { "bsm.execenv.elt64", T_STR, "bsm execenv: element no. 64" },
  { "bsm.execenv.elt65", T_STR, "bsm execenv: element no. 65" },
  { "bsm.execenv.elt66", T_STR, "bsm execenv: element no. 66" },
  { "bsm.execenv.elt67", T_STR, "bsm execenv: element no. 67" },
  { "bsm.execenv.elt68", T_STR, "bsm execenv: element no. 68" },
  { "bsm.execenv.elt69", T_STR, "bsm execenv: element no. 69" },
  { "bsm.execenv.elt70", T_STR, "bsm execenv: element no. 70" },
  { "bsm.execenv.elt71", T_STR, "bsm execenv: element no. 71" },
  { "bsm.execenv.elt72", T_STR, "bsm execenv: element no. 72" },
  { "bsm.execenv.elt73", T_STR, "bsm execenv: element no. 73" },
  { "bsm.execenv.elt74", T_STR, "bsm execenv: element no. 74" },
  { "bsm.execenv.elt75", T_STR, "bsm execenv: element no. 75" },
  { "bsm.execenv.elt76", T_STR, "bsm execenv: element no. 76" },
  { "bsm.execenv.elt77", T_STR, "bsm execenv: element no. 77" },
  { "bsm.execenv.elt78", T_STR, "bsm execenv: element no. 78" },
  { "bsm.execenv.elt79", T_STR, "bsm execenv: element no. 79" },
  { "bsm.execenv.elt80", T_STR, "bsm execenv: element no. 80" },
  { "bsm.execenv.elt81", T_STR, "bsm execenv: element no. 81" },
  { "bsm.execenv.elt82", T_STR, "bsm execenv: element no. 82" },
  { "bsm.execenv.elt83", T_STR, "bsm execenv: element no. 83" },
  { "bsm.execenv.elt84", T_STR, "bsm execenv: element no. 84" },
  { "bsm.execenv.elt85", T_STR, "bsm execenv: element no. 85" },
  { "bsm.execenv.elt86", T_STR, "bsm execenv: element no. 86" },
  { "bsm.execenv.elt87", T_STR, "bsm execenv: element no. 87" },
  { "bsm.execenv.elt88", T_STR, "bsm execenv: element no. 88" },
  { "bsm.execenv.elt89", T_STR, "bsm execenv: element no. 89" },
  { "bsm.execenv.elt90", T_STR, "bsm execenv: element no. 90" },
  { "bsm.execenv.elt91", T_STR, "bsm execenv: element no. 91" },
  { "bsm.execenv.elt92", T_STR, "bsm execenv: element no. 92" },
  { "bsm.execenv.elt93", T_STR, "bsm execenv: element no. 93" },
  { "bsm.execenv.elt94", T_STR, "bsm execenv: element no. 94" },
  { "bsm.execenv.elt95", T_STR, "bsm execenv: element no. 95" },
  { "bsm.execenv.elt96", T_STR, "bsm execenv: element no. 96" },
  { "bsm.execenv.elt97", T_STR, "bsm execenv: element no. 97" },
  { "bsm.execenv.elt98", T_STR, "bsm execenv: element no. 98" },
  { "bsm.execenv.elt99", T_STR, "bsm execenv: element no. 99" },
  { "bsm.execenv.elt100", T_STR, "bsm execenv: element no. 100" },
  { "bsm.execenv.elt101", T_STR, "bsm execenv: element no. 101" },
  { "bsm.execenv.elt102", T_STR, "bsm execenv: element no. 102" },
  { "bsm.execenv.elt103", T_STR, "bsm execenv: element no. 103" },
  { "bsm.execenv.elt104", T_STR, "bsm execenv: element no. 104" },
  { "bsm.execenv.elt105", T_STR, "bsm execenv: element no. 105" },
  { "bsm.execenv.elt106", T_STR, "bsm execenv: element no. 106" },
  { "bsm.execenv.elt107", T_STR, "bsm execenv: element no. 107" },
  { "bsm.execenv.elt108", T_STR, "bsm execenv: element no. 108" },
  { "bsm.execenv.elt109", T_STR, "bsm execenv: element no. 109" },
  { "bsm.execenv.elt110", T_STR, "bsm execenv: element no. 110" },
  { "bsm.execenv.elt111", T_STR, "bsm execenv: element no. 111" },
  { "bsm.execenv.elt112", T_STR, "bsm execenv: element no. 112" },
  { "bsm.execenv.elt113", T_STR, "bsm execenv: element no. 113" },
  { "bsm.execenv.elt114", T_STR, "bsm execenv: element no. 114" },
  { "bsm.execenv.elt115", T_STR, "bsm execenv: element no. 115" },
  { "bsm.execenv.elt116", T_STR, "bsm execenv: element no. 116" },
  { "bsm.execenv.elt117", T_STR, "bsm execenv: element no. 117" },
  { "bsm.execenv.elt118", T_STR, "bsm execenv: element no. 118" },
  { "bsm.execenv.elt119", T_STR, "bsm execenv: element no. 119" },
  { "bsm.execenv.elt120", T_STR, "bsm execenv: element no. 120" },
  { "bsm.execenv.elt121", T_STR, "bsm execenv: element no. 121" },
  { "bsm.execenv.elt122", T_STR, "bsm execenv: element no. 122" },
  { "bsm.execenv.elt123", T_STR, "bsm execenv: element no. 123" },
  { "bsm.execenv.elt124", T_STR, "bsm execenv: element no. 124" },
  { "bsm.execenv.elt125", T_STR, "bsm execenv: element no. 125" },
  { "bsm.execenv.elt126", T_STR, "bsm execenv: element no. 126" },
  { "bsm.execenv.elt127", T_STR, "bsm execenv: element no. 127" },
  { "bsm.execenv.elt128", T_STR, "bsm execenv: element no. 128" },
  { "bsm.arg1", T_INT, "bsm argument 1" },
  { "bsm.arg2", T_INT, "bsm argument 2" },
  { "bsm.arg3", T_INT, "bsm argument 3" },
  { "bsm.arg4", T_INT, "bsm argument 4" },
  { "bsm.arg5", T_INT, "bsm argument 5" },
  { "bsm.arg6", T_INT, "bsm argument 6" },
  { "bsm.arg7", T_INT, "bsm argument 7" },
  { "bsm.arg8", T_INT, "bsm argument 8" },
  { "bsm.arg9", T_INT, "bsm argument 9" },
  { "bsm.arg10", T_INT, "bsm argument 10" },
  { "bsm.arg11", T_INT, "bsm argument 11" },
  { "bsm.arg12", T_INT, "bsm argument 12" },
  { "bsm.arg13", T_INT, "bsm argument 13" },
  { "bsm.arg14", T_INT, "bsm argument 14" },
  { "bsm.arg15", T_INT, "bsm argument 15" },
  { "bsm.arg16", T_INT, "bsm argument 16" },
  { "bsm.arg17", T_INT, "bsm argument 17" },
  { "bsm.arg18", T_INT, "bsm argument 18" },
  { "bsm.arg19", T_INT, "bsm argument 19" },
  { "bsm.arg20", T_INT, "bsm argument 20" },
  { "bsm.arg21", T_INT, "bsm argument 21" },
  { "bsm.arg22", T_INT, "bsm argument 22" },
  { "bsm.arg23", T_INT, "bsm argument 23" },
  { "bsm.arg24", T_INT, "bsm argument 24" },
  { "bsm.arg25", T_INT, "bsm argument 25" },
  { "bsm.arg26", T_INT, "bsm argument 26" },
  { "bsm.arg27", T_INT, "bsm argument 27" },
  { "bsm.arg28", T_INT, "bsm argument 28" },
  { "bsm.arg29", T_INT, "bsm argument 29" },
  { "bsm.arg30", T_INT, "bsm argument 30" },
  { "bsm.arg31", T_INT, "bsm argument 31" },
  { "bsm.arg32", T_INT, "bsm argument 32" },
  { "bsm.arg33", T_INT, "bsm argument 33" },
  { "bsm.arg34", T_INT, "bsm argument 34" },
  { "bsm.arg35", T_INT, "bsm argument 35" },
  { "bsm.arg36", T_INT, "bsm argument 36" },
  { "bsm.arg37", T_INT, "bsm argument 37" },
  { "bsm.arg38", T_INT, "bsm argument 38" },
  { "bsm.arg39", T_INT, "bsm argument 39" },
  { "bsm.arg40", T_INT, "bsm argument 40" },
  { "bsm.arg41", T_INT, "bsm argument 41" },
  { "bsm.arg42", T_INT, "bsm argument 42" },
  { "bsm.arg43", T_INT, "bsm argument 43" },
  { "bsm.arg44", T_INT, "bsm argument 44" },
  { "bsm.arg45", T_INT, "bsm argument 45" },
  { "bsm.arg46", T_INT, "bsm argument 46" },
  { "bsm.arg47", T_INT, "bsm argument 47" },
  { "bsm.arg48", T_INT, "bsm argument 48" },
  { "bsm.arg49", T_INT, "bsm argument 49" },
  { "bsm.arg50", T_INT, "bsm argument 50" },
  { "bsm.arg51", T_INT, "bsm argument 51" },
  { "bsm.arg52", T_INT, "bsm argument 52" },
  { "bsm.arg53", T_INT, "bsm argument 53" },
  { "bsm.arg54", T_INT, "bsm argument 54" },
  { "bsm.arg55", T_INT, "bsm argument 55" },
  { "bsm.arg56", T_INT, "bsm argument 56" },
  { "bsm.arg57", T_INT, "bsm argument 57" },
  { "bsm.arg58", T_INT, "bsm argument 58" },
  { "bsm.arg59", T_INT, "bsm argument 59" },
  { "bsm.arg60", T_INT, "bsm argument 60" },
  { "bsm.arg61", T_INT, "bsm argument 61" },
  { "bsm.arg62", T_INT, "bsm argument 62" },
  { "bsm.arg63", T_INT, "bsm argument 63" },
  { "bsm.arg64", T_INT, "bsm argument 64" },
  { "bsm.arg65", T_INT, "bsm argument 65" },
  { "bsm.arg66", T_INT, "bsm argument 66" },
  { "bsm.arg67", T_INT, "bsm argument 67" },
  { "bsm.arg68", T_INT, "bsm argument 68" },
  { "bsm.arg69", T_INT, "bsm argument 69" },
  { "bsm.arg70", T_INT, "bsm argument 70" },
  { "bsm.arg71", T_INT, "bsm argument 71" },
  { "bsm.arg72", T_INT, "bsm argument 72" },
  { "bsm.arg73", T_INT, "bsm argument 73" },
  { "bsm.arg74", T_INT, "bsm argument 74" },
  { "bsm.arg75", T_INT, "bsm argument 75" },
  { "bsm.arg76", T_INT, "bsm argument 76" },
  { "bsm.arg77", T_INT, "bsm argument 77" },
  { "bsm.arg78", T_INT, "bsm argument 78" },
  { "bsm.arg79", T_INT, "bsm argument 79" },
  { "bsm.arg80", T_INT, "bsm argument 80" },
  { "bsm.arg81", T_INT, "bsm argument 81" },
  { "bsm.arg82", T_INT, "bsm argument 82" },
  { "bsm.arg83", T_INT, "bsm argument 83" },
  { "bsm.arg84", T_INT, "bsm argument 84" },
  { "bsm.arg85", T_INT, "bsm argument 85" },
  { "bsm.arg86", T_INT, "bsm argument 86" },
  { "bsm.arg87", T_INT, "bsm argument 87" },
  { "bsm.arg88", T_INT, "bsm argument 88" },
  { "bsm.arg89", T_INT, "bsm argument 89" },
  { "bsm.arg90", T_INT, "bsm argument 90" },
  { "bsm.arg91", T_INT, "bsm argument 91" },
  { "bsm.arg92", T_INT, "bsm argument 92" },
  { "bsm.arg93", T_INT, "bsm argument 93" },
  { "bsm.arg94", T_INT, "bsm argument 94" },
  { "bsm.arg95", T_INT, "bsm argument 95" },
  { "bsm.arg96", T_INT, "bsm argument 96" },
  { "bsm.arg97", T_INT, "bsm argument 97" },
  { "bsm.arg98", T_INT, "bsm argument 98" },
  { "bsm.arg99", T_INT, "bsm argument 99" },
  { "bsm.arg100", T_INT, "bsm argument 100" },
  { "bsm.arg101", T_INT, "bsm argument 101" },
  { "bsm.arg102", T_INT, "bsm argument 102" },
  { "bsm.arg103", T_INT, "bsm argument 103" },
  { "bsm.arg104", T_INT, "bsm argument 104" },
  { "bsm.arg105", T_INT, "bsm argument 105" },
  { "bsm.arg106", T_INT, "bsm argument 106" },
  { "bsm.arg107", T_INT, "bsm argument 107" },
  { "bsm.arg108", T_INT, "bsm argument 108" },
  { "bsm.arg109", T_INT, "bsm argument 109" },
  { "bsm.arg110", T_INT, "bsm argument 110" },
  { "bsm.arg111", T_INT, "bsm argument 111" },
  { "bsm.arg112", T_INT, "bsm argument 112" },
  { "bsm.arg113", T_INT, "bsm argument 113" },
  { "bsm.arg114", T_INT, "bsm argument 114" },
  { "bsm.arg115", T_INT, "bsm argument 115" },
  { "bsm.arg116", T_INT, "bsm argument 116" },
  { "bsm.arg117", T_INT, "bsm argument 117" },
  { "bsm.arg118", T_INT, "bsm argument 118" },
  { "bsm.arg119", T_INT, "bsm argument 119" },
  { "bsm.arg120", T_INT, "bsm argument 120" },
  { "bsm.arg121", T_INT, "bsm argument 121" },
  { "bsm.arg122", T_INT, "bsm argument 122" },
  { "bsm.arg123", T_INT, "bsm argument 123" },
  { "bsm.arg124", T_INT, "bsm argument 124" },
  { "bsm.arg125", T_INT, "bsm argument 125" },
  { "bsm.arg126", T_INT, "bsm argument 126" },
  { "bsm.arg127", T_INT, "bsm argument 127" },
  { "bsm.arg128", T_INT, "bsm argument 128" },
