%%
%% mod_prolog.pl prolog helpers
%%

% best interface:
listing_html(F) :-
    findall([Stream, Fname, Fd], stream_property(Stream, file_no(Fd)), StreamList), write(StreamList),
%    integer(Fd),
%    stream_property(OutStream, file_no(Fd)),
%    current_output(Curr_out),
%    set_output(OutStream),
%    listing,
%    flush_output(OutStream),
%    set_output(Curr_out),
    write('blah'),
    flush_output.
%    write(OutStream).

prolog_htmloutput(PipeCmd) :-
	current_output(Curr_out),
	open( pipe(PipeCmd), write, Stream),
	set_output(Stream),
	listing,
	set_output(Curr_out),
	close(Stream).

generate_listing_html(File) :-
	current_output(Curr_out),
	open(File, write, Fd),
	set_output(Fd),
	print_html_header,
	print_html_title,
	print_html_listing,
	print_html_trailer,
	set_output(Curr_out),
	close(Fd).

generate_listing_html_pipe(File) :-
	current_output(Curr_out),
	atom_concat('source-highlight -s prolog >> ', File, PipeCmd),
	open( pipe(PipeCmd), write, Fd),
	set_output(Fd),
	print_html_header,
	print_html_title,
	print_html_listing,
	print_html_trailer,
	set_output(Curr_out),
	close(Fd).

generate_listing_html_fd(Fd) :-
	integer(Fd),
	current_output(Curr_out),
	stream_property(Stream, file_no(Fd)),
	set_output(Stream),
	print_html_header,
	print_html_title,
	print_html_listing,
	print_html_trailer,
	set_output(Curr_out).

print_html_header :-
	write('<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n'),
	write('<html>\n'),
	write('<head>\n'),
	write('<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\n'),
	write('<title>Orchids Prolog Database</title>\n'),
	write('<meta http-equiv=\"content-type\" content=\"text/html; charset=ISO-8859-1\">\n'),
	write('<meta http-equiv=\"pragma\" content=\"no-cache\">\n'),
	write('<meta http-equiv=\"cache-control\" content=\"no-cache\">\n'),
	write('<meta http-equiv=\"refresh\" content=\"10\">'),
	write('</head>\n'),
	write('<body>\n').

print_html_title :-
	write('<center><h1>Orchids Prolog Database</h1></center>\n').

print_html_listing :-
	write('<center>'),
	write('<table border=\"0\" cellpadding=\"3\" width=\"600\">'),
	write('<tr><td class=\"v1\">'),
	write('<pre>\n'),
	listing,
	write('</pre>'),
	write('</td></tr>'),
	write('</table>'),
	write('</center>\n').

print_html_trailer :-
	get_time(Time),
	convert_time(Time, TimeStr),
	write('<br/><p align=\"right\"><small>'),
	write('Generated by <a href=\"http://www.lsv.ens-cachan.fr/orchids/\">Orchids</a>. '),
	write(TimeStr),
	write('</small></p>\n'),
	write('</body>\n'),
	write('<html>\n').
