#!/bin/sh

export DISTDIR=../../dist

export CONFIG_FILE=orchids-config.sh.dist
cat <<EOT >$CONFIG_FILE
#!/bin/sh
# Orchids configuration helper utility
# Automatically generated by config-utils.sh
# Use it to make sure Orchids lives in a sanely configured environment
EOT

source config-auditctl.sh
